<?php
/** Text fields of the "blog" page that update instantly in the Customizer preview. Generated by tools/mark-editable.py. */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'page_heading_heading_1',
	'page_heading_paragraph_1',
	'page_heading_small_heading_1',
	'ticket_grid_button_1',
	'ticket_grid_heading_1',
	'ticket_grid_heading_2',
	'ticket_grid_heading_3',
	'ticket_grid_heading_4',
	'ticket_grid_heading_5',
	'ticket_grid_heading_6',
	'ticket_grid_heading_7',
	'ticket_grid_paragraph_1',
	'ticket_grid_small_heading_1',
	'ticket_grid_small_heading_2',
	'ticket_grid_small_heading_3',
	'ticket_grid_small_heading_4',
	'ticket_grid_small_heading_5',
	'ticket_grid_text_1',
	'ticket_grid_text_10',
	'ticket_grid_text_11',
	'ticket_grid_text_12',
	'ticket_grid_text_13',
	'ticket_grid_text_2',
	'ticket_grid_text_3',
	'ticket_grid_text_4',
	'ticket_grid_text_5',
	'ticket_grid_text_6',
	'ticket_grid_text_7',
	'ticket_grid_text_8',
	'ticket_grid_text_9',
);
