<?php
/** Text fields of the "contact" page that update instantly in the Customizer preview. Generated by tools/mark-editable.py. */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'bottom_sticky_consultancy_bo_text_1',
	'contact_button_1',
	'contact_button_2',
	'contact_button_3',
	'contact_button_4',
	'contact_heading_1',
	'contact_heading_2',
	'contact_link_1',
	'contact_paragraph_1',
	'contact_small_heading_1',
	'contact_text_1',
	'next_heading_1',
	'next_heading_2',
	'next_heading_3',
	'next_heading_4',
	'next_paragraph_1',
	'next_paragraph_2',
	'next_paragraph_3',
	'next_small_heading_1',
);
