<?php
/** Text fields of the "cookies" page that update instantly in the Customizer preview. Generated by tools/mark-editable.py. */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'legal_emphasis_1',
	'legal_heading_1',
	'legal_link_1',
	'legal_link_2',
	'legal_link_3',
	'legal_link_4',
	'legal_link_5',
	'legal_link_6',
	'legal_paragraph_1',
	'legal_paragraph_2',
	'legal_paragraph_3',
	'legal_paragraph_4',
	'legal_paragraph_8',
	'legal_paragraph_9',
	'legal_small_heading_1',
	'legal_text_1',
	'legal_text_2',
	'legal_text_3',
);
