<?php
/** Text fields of the "events" page that update instantly in the Customizer preview. Generated by tools/mark-editable.py. */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'page_heading_heading_1',
	'page_heading_paragraph_1',
	'page_heading_small_heading_1',
	'ticket_grid_button_1',
	'ticket_grid_heading_1',
	'ticket_grid_paragraph_1',
	'ticket_grid_small_heading_1',
	'ticket_grid_text_1',
	'ticket_grid_text_2',
	'ticket_grid_text_3',
);
