<?php
/** Text fields of the "gallery" page that update instantly in the Customizer preview. Generated by tools/mark-editable.py. */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'page_heading_heading_1',
	'page_heading_paragraph_1',
	'page_heading_small_heading_1',
	'ticket_photo_grid_text_1',
	'ticket_photo_grid_text_10',
	'ticket_photo_grid_text_11',
	'ticket_photo_grid_text_12',
	'ticket_photo_grid_text_13',
	'ticket_photo_grid_text_14',
	'ticket_photo_grid_text_15',
	'ticket_photo_grid_text_16',
	'ticket_photo_grid_text_17',
	'ticket_photo_grid_text_18',
	'ticket_photo_grid_text_19',
	'ticket_photo_grid_text_2',
	'ticket_photo_grid_text_20',
	'ticket_photo_grid_text_21',
	'ticket_photo_grid_text_22',
	'ticket_photo_grid_text_23',
	'ticket_photo_grid_text_3',
	'ticket_photo_grid_text_4',
	'ticket_photo_grid_text_5',
	'ticket_photo_grid_text_6',
	'ticket_photo_grid_text_7',
	'ticket_photo_grid_text_8',
	'ticket_photo_grid_text_9',
);
