<?php
/** Text fields of the "not_found" page that update instantly in the Customizer preview. Generated by tools/mark-editable.py. */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'page_button_1',
	'page_button_2',
	'page_heading_1',
	'page_heading_2',
	'page_heading_3',
	'page_heading_4',
	'page_heading_5',
	'page_paragraph_1',
	'page_paragraph_2',
	'page_paragraph_3',
	'page_paragraph_4',
	'page_paragraph_5',
	'page_small_heading_1',
	'page_text_1',
	'page_text_2',
	'page_text_3',
);
