<?php
/** Text fields of the "single_post" page that update instantly in the Customizer preview. Generated by tools/mark-editable.py. */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'article_small_heading_1',
	'article_text_1',
	'article_text_2',
	'breadcrumb_link_1',
	'breadcrumb_link_2',
);
