<?php
/** Text fields of the "single_event" page that update instantly in the Customizer preview. Generated by tools/mark-editable.py. */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'breadcrumb_link_1',
	'breadcrumb_link_2',
	'event_details_button_1',
	'event_details_button_2',
	'event_details_heading_1',
	'event_details_heading_2',
	'you_might_also_like_heading_1',
	'you_might_also_like_text_1',
	'you_might_also_like_text_2',
);
