<?php
/** Text fields of the "sponsors" page that update instantly in the Customizer preview. Generated by tools/mark-editable.py. */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'partner_wall_heading_1',
	'partner_wall_paragraph_1',
	'partner_wall_small_heading_1',
	'partner_wall_text_1',
	'partner_wall_text_10',
	'partner_wall_text_11',
	'partner_wall_text_12',
	'partner_wall_text_13',
	'partner_wall_text_2',
	'partner_wall_text_3',
	'partner_wall_text_4',
	'partner_wall_text_5',
	'partner_wall_text_6',
	'partner_wall_text_7',
	'partner_wall_text_8',
	'partner_wall_text_9',
	'sponsors_heading_button_1',
	'sponsors_heading_button_2',
	'sponsors_heading_heading_2',
	'sponsors_heading_paragraph_1',
	'sponsors_heading_small_heading_1',
);
