<?php
/**
 * Replaceable photos of the "about" page: field => region, label, type, original photo id.
 * Generated by tools/extract-page-images.py; labels may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'hero_photo_1' => array( 'Hero', 'Hero: photo 1', 'media', '5d2ff88df9e44a1a073b23c7eb8ac29d' ),
	'hero_photo_2' => array( 'Hero', 'Hero: photo 2', 'media', '5b1a6ab37f0230a96cac807ce57c7983' ),
	'hero_photo_3' => array( 'Hero', 'Hero: photo 3', 'media', 'c5afda4fc4e4d4b0682377d6eb272c90' ),
	'what_we_do_photo_1' => array( 'What We Do', 'What We Do: photo 1', 'media', 'bf598dabf623c991f65ec61b98d88a5a' ),
	'what_we_do_photo_2' => array( 'What We Do', 'What We Do: photo 2', 'media', '6e1036b74f617a3d1887a7cf36398cff' ),
	'what_we_do_photo_3' => array( 'What We Do', 'What We Do: photo 3', 'media', 'b1e68ef21b53acd6fc513694c97d58cd' ),
	'what_we_do_photo_4' => array( 'What We Do', 'What We Do: photo 4', 'media', 'cf1ceb83917462889e44cacbaceaa722' ),
	'what_we_do_photo_5' => array( 'What We Do', 'What We Do: photo 5', 'media', '848d8e1043a6ef12d1cc8d2c2844ece2' ),
	'what_we_do_photo_6' => array( 'What We Do', 'What We Do: photo 6', 'media', '53d4feb181f3c6e0619a155bc4be2bf5' ),
	'what_we_do_photo_7' => array( 'What We Do', 'What We Do: photo 7', 'media', 'ca942693739cdc74700f9c8d65278358' ),
	'what_we_do_photo_8' => array( 'What We Do', 'What We Do: photo 8', 'media', '62f016a3e0b0dc275a615ae5af6b3b69' ),
	'what_we_do_photo_9' => array( 'What We Do', 'What We Do: photo 9', 'media', '8f4495361437a1d1961471650d55c60a' ),
	'what_we_do_photo_10' => array( 'What We Do', 'What We Do: photo 10', 'media', '44b7a98d85fefb8a03f8b8e625e3bcdc' ),
	'founder_photo_1' => array( 'Founder', 'Founder: photo 1 (Olabamidele \'Bambad\' Badmos, founder of Crux Nxtion)', 'media', 'a67d85c16f6df90ab7a657160bee9088' ),
);
