<?php
/**
 * Replaceable photos of the "consultancy" page: field => region, label, type, original photo id.
 * Generated by tools/extract-page-images.py; labels may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'sound_familiar_photo_1' => array( 'Sound Familiar', 'Sound Familiar: photo 1', 'media', '19a249fe66d9d8620a7283402ecde11e' ),
	'sound_familiar_photo_2' => array( 'Sound Familiar', 'Sound Familiar: photo 2', 'media', '53d4feb181f3c6e0619a155bc4be2bf5' ),
	'sound_familiar_photo_3' => array( 'Sound Familiar', 'Sound Familiar: photo 3', 'media', 'a4f578a4b1ff3c642674f670e1eaa25b' ),
	'sound_familiar_photo_4' => array( 'Sound Familiar', 'Sound Familiar: photo 4', 'media', '8f4495361437a1d1961471650d55c60a' ),
	'sound_familiar_photo_5' => array( 'Sound Familiar', 'Sound Familiar: photo 5', 'media', '44b7a98d85fefb8a03f8b8e625e3bcdc' ),
	'what_we_do_photo_1' => array( 'What We Do', 'What We Do: photo 1 (Setup & Strategy)', 'media', '4f18304ff3dad6215b2bb23021322a98' ),
	'what_we_do_photo_2' => array( 'What We Do', 'What We Do: photo 2 (Branding & Marketing)', 'media', 'ca942693739cdc74700f9c8d65278358' ),
	'what_we_do_photo_3' => array( 'What We Do', 'What We Do: photo 3 (Operations & Workflow)', 'media', '62f016a3e0b0dc275a615ae5af6b3b69' ),
	'what_we_do_photo_4' => array( 'What We Do', 'What We Do: photo 4 (Growth & Scaling)', 'media', 'b7834baeaf5a08921ea7b06e7153a0e4' ),
	'what_we_do_photo_5' => array( 'What We Do', 'What We Do: photo 5 (Event Advisory)', 'media', '052d83d28ee851b93069420ea3c10f8f' ),
	'how_it_works_photo_1' => array( 'How It Works', 'How It Works: photo 1', 'media', '50cb2790126aab1196125a6f09c951bf' ),
	'how_it_works_photo_2' => array( 'How It Works', 'How It Works: photo 2', 'media', '052d83d28ee851b93069420ea3c10f8f' ),
	'how_it_works_photo_3' => array( 'How It Works', 'How It Works: photo 3', 'media', 'e56c3376aee5c9f5027ad93a6f335536' ),
	'how_it_works_photo_4' => array( 'How It Works', 'How It Works: photo 4', 'media', '97f6e11f46029a4f9812d43722c1bcf4' ),
	'how_it_works_photo_5' => array( 'How It Works', 'How It Works: photo 5', 'media', '263030a5b7aa9f782aeddd3e7f44cb13' ),
	'what_you_walk_away_with_photo_1' => array( 'What You Walk Away With', 'What You Walk Away With: photo 1', 'media', '8cbbf8075ea65369e575c4f2b9fd9e4c' ),
	'what_you_walk_away_with_photo_2' => array( 'What You Walk Away With', 'What You Walk Away With: photo 2', 'media', 'd7ec7e8129482dec3e004a136575df53' ),
	'why_us_photo_1' => array( 'Why Us', 'Why Us: photo 1', 'media', 'c5afda4fc4e4d4b0682377d6eb272c90' ),
	'why_us_photo_2' => array( 'Why Us', 'Why Us: photo 2', 'media', '5d2ff88df9e44a1a073b23c7eb8ac29d' ),
	'why_us_photo_3' => array( 'Why Us', 'Why Us: photo 3', 'media', 'b1e68ef21b53acd6fc513694c97d58cd' ),
	'meet_the_strategic_team_foun_photo_1' => array( 'Meet The Strategic Team / Founder', 'Meet The Strategic Team / Founder: photo 1 (Olabamidele \'Bambad\' Badmos)', 'media', 'a67d85c16f6df90ab7a657160bee9088' ),
	'faq_photo_1' => array( 'Faq', 'Faq: photo 1', 'media', 'de1f229044e51fea8eef0e8e07331cbe' ),
);
