<?php
/**
 * Replaceable photos of the "contact" page: field => region, label, type, original photo id.
 * Generated by tools/extract-page-images.py; labels may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'contact_photo_1' => array( 'Contact page', 'Photo 1', 'media', '4170d6b6009c07e37d83bae48a68917b' ),
);
