<?php
/**
 * Replaceable photos of the "founder" page: field => region, label, type, original photo id.
 * Generated by tools/extract-page-images.py; labels may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'about_meet_the_team_hero_photo_1' => array( 'About / Meet The Team Hero', 'About / Meet The Team Hero: photo 1 (Olabamidele \'Bambad\' Badmos)', 'media', 'a67d85c16f6df90ab7a657160bee9088' ),
);
