<?php
/**
 * Replaceable photos of the "gallery" page: field => region, label, type, original photo id.
 * Generated by tools/extract-page-images.py; labels may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'ticket_photo_grid_photo_1' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: photo 1 (Crux Nxtion Events frame 1)', 'media', 'feb81852032e2798160126ebf0d3c7f6' ),
	'ticket_photo_grid_photo_2' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: photo 2 (Crux Nxtion Events frame 2)', 'media', '4170d6b6009c07e37d83bae48a68917b' ),
	'ticket_photo_grid_photo_3' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: photo 3 (Crux Nxtion Events frame 3)', 'media', 'c5afda4fc4e4d4b0682377d6eb272c90' ),
	'ticket_photo_grid_photo_4' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: photo 4 (Crux Nxtion Events frame 4)', 'media', 'b670d3a0bfa370687d246a6ab941625c' ),
	'ticket_photo_grid_photo_5' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: photo 5 (Crux Nxtion Events frame 5)', 'media', '2fe0208788cf2d50763c85dd2a44de66' ),
	'ticket_photo_grid_photo_6' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: photo 6 (Crux Nxtion Events frame 6)', 'media', '1d5292715423e2e83b56b3330a94b3b8' ),
	'ticket_photo_grid_photo_7' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: photo 7 (Crux Nxtion Events frame 7)', 'media', '99a3c292f4b3a38d253144801b4a9ae3' ),
	'ticket_photo_grid_photo_8' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: photo 8 (Crux Nxtion Events frame 8)', 'media', '8f947f32de7fe00cf711036348e00351' ),
	'ticket_photo_grid_photo_9' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: photo 9 (Crux Nxtion Events frame 10)', 'media', '2b696c907bf5b4d0dc14a80e8cd60e15' ),
	'ticket_photo_grid_photo_10' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: photo 10 (Crux Nxtion Events frame 11)', 'media', 'e6e06da1a649b213d8dd573ea6511302' ),
	'ticket_photo_grid_photo_11' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: photo 11 (Crux Nxtion Events frame 12)', 'media', 'b094675514894aa0d8e7dd735d187b22' ),
	'ticket_photo_grid_photo_12' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: photo 12 (Crux Nxtion Events frame 13)', 'media', '00a901525823b7149b4ebb66e5a9678f' ),
	'ticket_photo_grid_photo_13' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: photo 13 (Crux Nxtion Events frame 14)', 'media', '5e2df00e7ead10292f7266fc033953c3' ),
	'ticket_photo_grid_photo_14' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: photo 14 (Crux Nxtion Events frame 15)', 'media', '2643e6061a232eeda4f8344fe6df6166' ),
);
