<?php
/**
 * Replaceable photos of the "home" page: field => region, label, type, original photo id.
 * Generated by tools/extract-page-images.py; labels may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'hero_photo_1' => array( 'Top banner', 'Photo 1: Crowd dancing at a Crux Nxtion Events event', 'media', '5e2df00e7ead10292f7266fc033953c3' ),
	'services_photo_1' => array( 'Services list', 'Photo 1', 'media', 'e6e06da1a649b213d8dd573ea6511302' ),
	'services_photo_2' => array( 'Services list', 'Photo 2', 'media', '6e1036b74f617a3d1887a7cf36398cff' ),
	'services_photo_3' => array( 'Services list', 'Photo 3', 'media', 'c5afda4fc4e4d4b0682377d6eb272c90' ),
	'services_photo_4' => array( 'Services list', 'Photo 4', 'media', 'feb81852032e2798160126ebf0d3c7f6' ),
	'services_photo_5' => array( 'Services list', 'Photo 5', 'media', '2b696c907bf5b4d0dc14a80e8cd60e15' ),
	'also_from_crux_photo_1' => array( 'Consultancy promo', 'Photo 1: A Crux Nxtion Consultancy session', 'media', '5b1a6ab37f0230a96cac807ce57c7983' ),
	'gallery_photo_1' => array( 'Gallery strip', 'Photo 1: Crux Nxtion Events frame 1', 'media', '8779e5d9192fb628e623a9aec1f82362' ),
	'gallery_photo_2' => array( 'Gallery strip', 'Photo 2: Crux Nxtion Events frame 2', 'media', '4170d6b6009c07e37d83bae48a68917b' ),
	'gallery_photo_3' => array( 'Gallery strip', 'Photo 3: Crux Nxtion Events frame 3', 'media', 'c5afda4fc4e4d4b0682377d6eb272c90' ),
	'why_crux_photo_1' => array( 'Why choose us', 'Photo 1', 'media', '2fe0208788cf2d50763c85dd2a44de66' ),
	'why_crux_photo_2' => array( 'Why choose us', 'Photo 2', 'media', '6aa60ee4af0bdb49015bf4224786bd46' ),
	'why_crux_photo_3' => array( 'Why choose us', 'Photo 3', 'media', 'a7f19688f4ec09c5590ca71c99b9f400' ),
	'process_photo_1' => array( 'How we work', 'Photo 1', 'media', '7ad16fa711374cf636fa630f0cf398c0' ),
	'process_photo_2' => array( 'How we work', 'Photo 2', 'media', '4795dc48859e2b9d81b42757c6317d14' ),
	'process_photo_3' => array( 'How we work', 'Photo 3', 'media', '8127c7ab2af037f167d7a8b67413ab45' ),
	'process_photo_4' => array( 'How we work', 'Photo 4', 'media', 'f1ffd7a776c034eaead72759fb4440c6' ),
	'mini_about_photo_1' => array( 'Short about', 'Photo 1', 'media', 'fbd294c148cb8e1a55a31856bc061a40' ),
	'mini_about_photo_2' => array( 'Short about', 'Photo 2', 'media', 'c5afda4fc4e4d4b0682377d6eb272c90' ),
	'mini_about_photo_3' => array( 'Short about', 'Photo 3', 'media', '3f7a3d27a340e99222e15e9e60a98a7d' ),
	'founder_photo_1' => array( 'Founder and team', 'Photo 1: Olabamidele \'Bambad\' Badmos, founder of Crux Nxtion', 'media', 'a67d85c16f6df90ab7a657160bee9088' ),
);
