<?php
/**
 * Replaceable photos of the "services_consultancy" page: field => region, label, type, original photo id.
 * Generated by tools/extract-page-images.py; labels may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'page_heading_photo_1' => array( 'Page content', 'Photo 1', 'media', '53d4feb181f3c6e0619a155bc4be2bf5' ),
	'page_heading_photo_2' => array( 'Page content', 'Photo 2', 'media', 'ca942693739cdc74700f9c8d65278358' ),
	'page_heading_photo_3' => array( 'Page content', 'Photo 3', 'media', '62f016a3e0b0dc275a615ae5af6b3b69' ),
	'page_heading_photo_4' => array( 'Page content', 'Photo 4', 'media', '8f4495361437a1d1961471650d55c60a' ),
	'page_heading_photo_5' => array( 'Page content', 'Photo 5', 'media', '44b7a98d85fefb8a03f8b8e625e3bcdc' ),
);
