<?php
/**
 * Replaceable photos of the "services" page: field => region, label, type, original photo id.
 * Generated by tools/extract-page-images.py; labels may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'service_rows_photo_1' => array( 'Service Rows', 'Service Rows: photo 1', 'media', 'c5afda4fc4e4d4b0682377d6eb272c90' ),
	'service_rows_photo_2' => array( 'Service Rows', 'Service Rows: photo 2', 'media', '2fe0208788cf2d50763c85dd2a44de66' ),
	'service_rows_photo_3' => array( 'Service Rows', 'Service Rows: photo 3', 'media', '8f947f32de7fe00cf711036348e00351' ),
	'service_rows_photo_4' => array( 'Service Rows', 'Service Rows: photo 4', 'media', '2b696c907bf5b4d0dc14a80e8cd60e15' ),
	'service_rows_photo_5' => array( 'Service Rows', 'Service Rows: photo 5', 'media', 'e6e06da1a649b213d8dd573ea6511302' ),
	'process_photo_1' => array( 'Process', 'Process: photo 1', 'media', 'fbd294c148cb8e1a55a31856bc061a40' ),
	'process_photo_2' => array( 'Process', 'Process: photo 2', 'media', '4170d6b6009c07e37d83bae48a68917b' ),
	'process_photo_3' => array( 'Process', 'Process: photo 3', 'media', '1d5292715423e2e83b56b3330a94b3b8' ),
	'process_photo_4' => array( 'Process', 'Process: photo 4', 'media', 'c5afda4fc4e4d4b0682377d6eb272c90' ),
);
