<?php
/**
 * Replaceable photos of the "sponsors" page: field => region, label, type, original photo id.
 * Generated by tools/extract-page-images.py; labels may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'sponsors_heading_photo_1' => array( 'Page heading', 'Photo 1: Vendors serving guests at a Crux Nxtion event', 'media', '2b696c907bf5b4d0dc14a80e8cd60e15' ),
	'partner_wall_photo_1' => array( 'Partner wall', 'Photo 1: Crux Nxtion partner', 'media', '3e237813fb9f6842a00a00f493717e50' ),
	'partner_wall_photo_2' => array( 'Partner wall', 'Photo 2: Crux Nxtion partner', 'media', 'abbeaf5f563caf0a36336c5e0219cdc0' ),
	'partner_wall_photo_3' => array( 'Partner wall', 'Photo 3', 'media', 'de1eac2cea70d9ffc75148b9accd0833' ),
	'partner_wall_photo_4' => array( 'Partner wall', 'Photo 4: Phemzy Studios', 'media', '0dabf904386bf3c567390a985651785e' ),
	'partner_wall_photo_5' => array( 'Partner wall', 'Photo 5: Crux Nxtion partner', 'media', '31c531a4db0e51855507e872d273fc64' ),
	'partner_wall_photo_6' => array( 'Partner wall', 'Photo 6: Dotun Omiyale', 'media', '0e3450f2f8f0a4ce5afd084843a3cb2f' ),
	'partner_wall_photo_7' => array( 'Partner wall', 'Photo 7: Crux Nxtion partner', 'media', 'e2d1c89ac716ea5f92ab8e31be53bade' ),
	'partner_wall_photo_8' => array( 'Partner wall', 'Photo 8: DJ03', 'media', '15e555b5257378f29e72ecde1fb7e5f3' ),
	'partner_wall_photo_9' => array( 'Partner wall', 'Photo 9: Crux Nxtion partner', 'media', '85b05c3630e70a76a40b1411919f2987' ),
	'partner_wall_photo_10' => array( 'Partner wall', 'Photo 10: D20 Pasties', 'media', '0f86db33ccd6204138c27980499a58e1' ),
	'partner_wall_photo_11' => array( 'Partner wall', 'Photo 11: Livingbangel Beauty Lounge', 'media', '2d13a2f72d6824fb6334d5366984c9df' ),
	'partner_wall_photo_12' => array( 'Partner wall', 'Photo 12: Food Emporium UK', 'media', '18373137dc739154d5a9c88a4f075201' ),
	'partner_wall_photo_13' => array( 'Partner wall', 'Photo 13: Crux Nxtion partner', 'media', '1a6f99c10b46fe8f6da34271f5eaf048' ),
	'partner_wall_photo_14' => array( 'Partner wall', 'Photo 14: Crux Nxtion partner', 'media', '5d9392be79f6ba3f1fb18b1923e80c13' ),
	'partner_wall_photo_15' => array( 'Partner wall', 'Photo 15: Sokid Photography', 'media', '4ae9886f77ee1545ce79727e031a2c76' ),
	'partner_wall_photo_16' => array( 'Partner wall', 'Photo 16: Zee Jewels', 'media', 'c205c0a2e87784d728fe729edd731e2e' ),
	'partner_wall_photo_17' => array( 'Partner wall', 'Photo 17: Rosella\'s Wonder', 'media', 'fc86f6756c4525131aadac80ca442a7b' ),
);
