<?php
/**
 * Editable wording of the "blog" page: field => section, label, type, original wording.
 * Generated by tools/extract-page-text.py; labels and sections may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'page_heading_small_heading_1' => array( 'Page Heading', 'Page Heading: small heading 1 (Notes From The Crew)', 'text', 'Notes From The Crew' ),
	'page_heading_heading_1' => array( 'Page Heading', 'Page Heading: heading 1 (THE JOURNAL)', 'text', 'THE JOURNAL' ),
	'page_heading_paragraph_1' => array( 'Page Heading', 'Page Heading: paragraph 1 (Event recaps, planning guides and...)', 'textarea', 'Event recaps, planning guides and stories from the crew — filed like a ticket, punched by the same people.' ),
	'ticket_grid_text_1' => array( 'Ticket Grid', 'Ticket Grid: text 1 (FEATURED)', 'text', 'FEATURED' ),
	'ticket_grid_small_heading_1' => array( 'Ticket Grid', 'Ticket Grid: small heading 1 (Event Recap)', 'text', 'Event Recap' ),
	'ticket_grid_heading_1' => array( 'Ticket Grid', 'Ticket Grid: heading 1 (BEHIND DANCE OUT 2023: HOW WE FILL...)', 'text', 'BEHIND DANCE OUT 2023: HOW WE FILL A DANCE FLOOR' ),
	'ticket_grid_paragraph_1' => array( 'Ticket Grid', 'Ticket Grid: paragraph 1 (A behind-the-scenes look at how on...)', 'textarea', 'A behind-the-scenes look at how one crew plans, books and runs a night built to keep people moving.' ),
	'ticket_grid_text_2' => array( 'Ticket Grid', 'Ticket Grid: text 2 (Read The Story →)', 'text', 'Read The Story →' ),
	'ticket_grid_text_3' => array( 'Ticket Grid', 'Ticket Grid: text 3 (GUIDES)', 'text', 'GUIDES' ),
	'ticket_grid_small_heading_2' => array( 'Ticket Grid', 'Ticket Grid: small heading 2 (Guides)', 'text', 'Guides' ),
	'ticket_grid_heading_2' => array( 'Ticket Grid', 'Ticket Grid: heading 2 (Planning A Nigerian Wedding Party...)', 'text', 'Planning A Nigerian Wedding Party In The UK' ),
	'ticket_grid_text_4' => array( 'Ticket Grid', 'Ticket Grid: text 4 (7 min read)', 'text', '7 min read' ),
	'ticket_grid_text_5' => array( 'Ticket Grid', 'Ticket Grid: text 5 (NOTES)', 'text', 'NOTES' ),
	'ticket_grid_small_heading_3' => array( 'Ticket Grid', 'Ticket Grid: small heading 3 (Behind The Scenes)', 'text', 'Behind The Scenes' ),
	'ticket_grid_heading_3' => array( 'Ticket Grid', 'Ticket Grid: heading 3 (What Entertainment Booking Really...)', 'text', 'What Entertainment Booking Really Involves' ),
	'ticket_grid_text_6' => array( 'Ticket Grid', 'Ticket Grid: text 6 (6 min read)', 'text', '6 min read' ),
	'ticket_grid_heading_4' => array( 'Ticket Grid', 'Ticket Grid: heading 4 (How Far Ahead Should You Book Your...)', 'text', 'How Far Ahead Should You Book Your Event?' ),
	'ticket_grid_text_7' => array( 'Ticket Grid', 'Ticket Grid: text 7 (5 min read)', 'text', '5 min read' ),
	'ticket_grid_text_8' => array( 'Ticket Grid', 'Ticket Grid: text 8 (STORY)', 'text', 'STORY' ),
	'ticket_grid_small_heading_4' => array( 'Ticket Grid', 'Ticket Grid: small heading 4 (Our Story)', 'text', 'Our Story' ),
	'ticket_grid_heading_5' => array( 'Ticket Grid', 'Ticket Grid: heading 5 (From Events Crew To Consultancy: W...)', 'text', 'From Events Crew To Consultancy: Why We Started' ),
	'ticket_grid_text_9' => array( 'Ticket Grid', 'Ticket Grid: text 9 (8 min read)', 'text', '8 min read' ),
	'ticket_grid_text_10' => array( 'Ticket Grid', 'Ticket Grid: text 10 (RECAP)', 'text', 'RECAP' ),
	'ticket_grid_heading_6' => array( 'Ticket Grid', 'Ticket Grid: heading 6 (Ankara Festival, In Photos)', 'text', 'Ankara Festival, In Photos' ),
	'ticket_grid_text_11' => array( 'Ticket Grid', 'Ticket Grid: text 11 (4 min read)', 'text', '4 min read' ),
	'ticket_grid_small_heading_5' => array( 'Ticket Grid', 'Ticket Grid: small heading 5 (Have A Story We Should Cover?)', 'text', 'Have A Story We Should Cover?' ),
	'ticket_grid_heading_7' => array( 'Ticket Grid', 'Ticket Grid: heading 7 (SEND US A NOTE)', 'text', 'SEND US A NOTE' ),
	'ticket_grid_button_1' => array( 'Ticket Grid', 'Ticket Grid: button 1 (Get In Touch)', 'text', 'Get In Touch' ),
	'ticket_grid_text_12' => array( 'Ticket Grid', 'Ticket Grid: text 12 (Events)', 'text', 'Events' ),
	'ticket_grid_text_13' => array( 'Ticket Grid', 'Ticket Grid: text 13 (Consultancy)', 'text', 'Consultancy' ),
);
