<?php
/**
 * Editable wording of the "blog" page: field => section, label, type, original wording.
 * Generated by tools/extract-page-text.py; labels and sections may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'page_heading_small_heading_1' => array( 'Page heading', 'Label above heading 1: Notes From The Crew', 'text', 'Notes From The Crew' ),
	'page_heading_heading_1' => array( 'Page heading', 'Heading 1: THE JOURNAL', 'text', 'THE JOURNAL' ),
	'page_heading_paragraph_1' => array( 'Page heading', 'Text 1: Event recaps, planning guides and...', 'textarea', 'Event recaps, planning guides and stories from the crew — filed like a ticket, punched by the same people.' ),
	'post_list_text_1' => array( 'Post list', 'Text 1: Read article link', 'text', 'Read article →' ),
	'post_list_text_2' => array( 'Post list', 'Text 2: message when there are no articles', 'text', 'No articles yet. Please check back soon.' ),
	'wing_switch_text_1' => array( 'Wing switch', 'Text 1: Events tab', 'text', 'Events' ),
	'wing_switch_text_2' => array( 'Wing switch', 'Text 2: Consultancy tab', 'text', 'Consultancy' ),
);
