<?php
/**
 * Editable wording of the "blog" page: field => section, label, type, original wording.
 * Generated by tools/extract-page-text.py; labels and sections may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'page_heading_small_heading_1' => array( 'Page heading', 'Label above heading 1: Notes From The Crew', 'text', 'Notes From The Crew' ),
	'page_heading_heading_1' => array( 'Page heading', 'Heading 1: THE JOURNAL', 'text', 'THE JOURNAL' ),
	'page_heading_paragraph_1' => array( 'Page heading', 'Text 1: Event recaps, planning guides and...', 'textarea', 'Event recaps, planning guides and stories from the crew — filed like a ticket, punched by the same people.' ),
	'ticket_grid_text_1' => array( 'Post list', 'Text 1: FEATURED', 'text', 'FEATURED' ),
	'ticket_grid_small_heading_1' => array( 'Post list', 'Label above heading 1: Event Recap', 'text', 'Event Recap' ),
	'ticket_grid_heading_1' => array( 'Post list', 'Heading 1: BEHIND DANCE OUT 2023: HOW WE FILL...', 'text', 'BEHIND DANCE OUT 2023: HOW WE FILL A DANCE FLOOR' ),
	'ticket_grid_paragraph_1' => array( 'Post list', 'Text 1: A behind-the-scenes look at how on...', 'textarea', 'A behind-the-scenes look at how one crew plans, books and runs a night built to keep people moving.' ),
	'ticket_grid_text_2' => array( 'Post list', 'Text 2: Read The Story →', 'text', 'Read The Story →' ),
	'ticket_grid_text_3' => array( 'Post list', 'Text 3: GUIDES', 'text', 'GUIDES' ),
	'ticket_grid_small_heading_2' => array( 'Post list', 'Label above heading 2: Guides', 'text', 'Guides' ),
	'ticket_grid_heading_2' => array( 'Post list', 'Heading 2: Planning A Nigerian Wedding Party...', 'text', 'Planning A Nigerian Wedding Party In The UK' ),
	'ticket_grid_text_4' => array( 'Post list', 'Text 4: 7 min read', 'text', '7 min read' ),
	'ticket_grid_text_5' => array( 'Post list', 'Text 5: NOTES', 'text', 'NOTES' ),
	'ticket_grid_small_heading_3' => array( 'Post list', 'Label above heading 3: Behind The Scenes', 'text', 'Behind The Scenes' ),
	'ticket_grid_heading_3' => array( 'Post list', 'Heading 3: What Entertainment Booking Really...', 'text', 'What Entertainment Booking Really Involves' ),
	'ticket_grid_text_6' => array( 'Post list', 'Text 6: 6 min read', 'text', '6 min read' ),
	'ticket_grid_heading_4' => array( 'Post list', 'Heading 4: How Far Ahead Should You Book Your...', 'text', 'How Far Ahead Should You Book Your Event?' ),
	'ticket_grid_text_7' => array( 'Post list', 'Text 7: 5 min read', 'text', '5 min read' ),
	'ticket_grid_text_8' => array( 'Post list', 'Text 8: STORY', 'text', 'STORY' ),
	'ticket_grid_small_heading_4' => array( 'Post list', 'Label above heading 4: Our Story', 'text', 'Our Story' ),
	'ticket_grid_heading_5' => array( 'Post list', 'Heading 5: From Events Crew To Consultancy: W...', 'text', 'From Events Crew To Consultancy: Why We Started' ),
	'ticket_grid_text_9' => array( 'Post list', 'Text 9: 8 min read', 'text', '8 min read' ),
	'ticket_grid_text_10' => array( 'Post list', 'Text 10: RECAP', 'text', 'RECAP' ),
	'ticket_grid_heading_6' => array( 'Post list', 'Heading 6: Ankara Festival, In Photos', 'text', 'Ankara Festival, In Photos' ),
	'ticket_grid_text_11' => array( 'Post list', 'Text 11: 4 min read', 'text', '4 min read' ),
	'ticket_grid_small_heading_5' => array( 'Post list', 'Label above heading 5: Have A Story We Should Cover?', 'text', 'Have A Story We Should Cover?' ),
	'ticket_grid_heading_7' => array( 'Post list', 'Heading 7: SEND US A NOTE', 'text', 'SEND US A NOTE' ),
	'ticket_grid_button_1' => array( 'Post list', 'Button 1: Get In Touch', 'text', 'Get In Touch' ),
	'ticket_grid_text_12' => array( 'Post list', 'Text 12: Events', 'text', 'Events' ),
	'ticket_grid_text_13' => array( 'Post list', 'Text 13: Consultancy', 'text', 'Consultancy' ),
);
