<?php
/**
 * Editable wording of the "contact" page: field => section, label, type, original wording.
 * Generated by tools/extract-page-text.py; labels and sections may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'contact_small_heading_1' => array( 'Contact', 'Contact: small heading 1 (Get In Touch)', 'text', 'Get In Touch' ),
	'contact_heading_1' => array( 'Contact', 'Contact: heading 1 (LET\'S TALK.)', 'text', 'LET\'S TALK.' ),
	'contact_button_1' => array( 'Contact', 'Contact: button 1 (Plan An Event)', 'text', 'Plan An Event' ),
	'contact_heading_2' => array( 'Contact', 'Contact: heading 2 (BRIEF RECEIVED!)', 'text', 'BRIEF RECEIVED!' ),
	'contact_text_1' => array( 'Contact', 'Contact: text 1 (Events Inquiry)', 'text', 'Events Inquiry' ),
	'contact_paragraph_1' => array( 'Contact', 'Contact: paragraph 1 (Thank you! Your brief has been tra...)', 'textarea', 'Thank you! Your brief has been transmitted directly to our team. A real person will review your requirements and reply within 24 business hours.' ),
	'contact_button_2' => array( 'Contact', 'Contact: button 2 (Book Discovery Call on Calendly →)', 'text', 'Book Discovery Call on Calendly →' ),
	'contact_button_3' => array( 'Contact', 'Contact: button 3 (Close & Continue)', 'text', 'Close & Continue' ),
	'contact_button_4' => array( 'Contact', 'Contact: button 4 (Send Another Brief)', 'text', 'Send Another Brief' ),
	'contact_link_1' => array( 'Contact', 'Contact: link 1 (Get directions →)', 'text', 'Get directions →' ),
	'next_small_heading_1' => array( 'Next', 'Next: small heading 1 (What Happens Next)', 'text', 'What Happens Next' ),
	'next_heading_1' => array( 'Next', 'Next: heading 1 (NO FORMS DISAPPEARING INTO THE VOID.)', 'text', 'NO FORMS DISAPPEARING INTO THE VOID.' ),
	'next_heading_2' => array( 'Next', 'Next: heading 2 (YOU SEND A BRIEF)', 'text', 'YOU SEND A BRIEF' ),
	'next_paragraph_1' => array( 'Next', 'Next: paragraph 1 (A few lines is plenty — what you\'r...)', 'text', 'A few lines is plenty — what you\'re planning, or where you\'re stuck.' ),
	'next_heading_3' => array( 'Next', 'Next: heading 3 (WE REPLY AND TALK IT THROUGH)', 'text', 'WE REPLY AND TALK IT THROUGH' ),
	'next_paragraph_2' => array( 'Next', 'Next: paragraph 2 (A real person comes back to you, u...)', 'text', 'A real person comes back to you, usually with a question or two.' ),
	'next_heading_4' => array( 'Next', 'Next: heading 4 (YOU GET A PLAN)', 'text', 'YOU GET A PLAN' ),
	'next_paragraph_3' => array( 'Next', 'Next: paragraph 3 (A clear next step, quote or propos...)', 'text', 'A clear next step, quote or proposal — whichever fits.' ),
	'bottom_sticky_consultancy_bo_text_1' => array( 'Bottom Sticky Consultancy Booking Button', 'Bottom Sticky Consultancy Booking Button: text 1 (Direct Consultancy Booking)', 'text', 'Direct Consultancy Booking' ),
);
