<?php
/**
 * Editable wording of the "cookies" page: field => section, label, type, original wording.
 * Generated by tools/extract-page-text.py; labels and sections may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'legal_small_heading_1' => array( 'Page text', 'Label above heading 1: Legal', 'text', 'Legal' ),
	'legal_heading_1' => array( 'Page text', 'Heading 1: COOKIE POLICY', 'text', 'COOKIE POLICY' ),
	'legal_paragraph_1' => array( 'Page text', 'Text 1: What cookies are, which ones we us...', 'text', 'What cookies are, which ones we use, and how to control them.' ),
	'legal_paragraph_2' => array( 'Page text', 'Text 2: Last updated 19 September 2026', 'text', 'Last updated 19 September 2026' ),
	'legal_text_1' => array( 'Page text', 'Text 1: ON THIS PAGE', 'text', 'ON THIS PAGE' ),
	'legal_link_1' => array( 'Page text', 'Link 1: 1. What are cookies', 'text', '1. What are cookies' ),
	'legal_link_2' => array( 'Page text', 'Link 2: 2. Cookies we use', 'text', '2. Cookies we use' ),
	'legal_link_3' => array( 'Page text', 'Link 3: 3. Third-party cookies', 'text', '3. Third-party cookies' ),
	'legal_link_4' => array( 'Page text', 'Link 4: 4. Managing your choices', 'text', '4. Managing your choices' ),
	'legal_link_5' => array( 'Page text', 'Link 5: 5. Contact', 'text', '5. Contact' ),
	'legal_emphasis_1' => array( 'Page text', 'Highlighted words 1: Questions?', 'text', 'Questions?' ),
	'legal_paragraph_3' => array( 'Page text', 'Text 3: Email us and a real person will re...', 'text', 'Email us and a real person will reply.' ),
	'legal_link_6' => array( 'Page text', 'Link 6: Contact us →', 'text', 'Contact us →' ),
	'legal_paragraph_4' => array( 'Page text', 'Text 4: Cookies are small text files store...', 'textarea', 'Cookies are small text files stored on your device when you visit a website. They help the site work, remember your choices and understand how it is used.' ),
	'legal_paragraph_5' => array( 'Page text', 'Text 5: Essential cookies keep the site se...', 'rich', '<b>Essential</b> cookies keep the site secure and working, for example remembering your cookie choice. They cannot be switched off.' ),
	'legal_paragraph_6' => array( 'Page text', 'Text 6: Analytics cookies help us understa...', 'rich', '<b>Analytics</b> cookies help us understand which pages are useful, using anonymous or aggregated data. We only set these if you accept.' ),
	'legal_paragraph_7' => array( 'Page text', 'Text 7: Marketing cookies, where used, hel...', 'rich', '<b>Marketing</b> cookies, where used, help us show relevant Crux Nxtion content on other platforms. We only set these if you accept.' ),
	'legal_paragraph_8' => array( 'Page text', 'Text 8: Some content, such as embedded vid...', 'textarea', 'Some content, such as embedded videos, maps, social feeds and ticketing pages, is provided by other companies who may set their own cookies. Please check their policies for details.' ),
	'legal_paragraph_9' => array( 'Page text', 'Text 9: You can change your consent at any...', 'textarea', 'You can change your consent at any time using the cookie settings link in the site footer. You can also block or delete cookies in your browser settings, but parts of the site may not work as intended.' ),
	'legal_paragraph_10' => array( 'Page text', 'Text 10: Questions about cookies? Email', 'text', 'Questions about cookies? Email' ),
	'legal_text_2' => array( 'Page text', 'Text 2: Events', 'text', 'Events' ),
	'legal_text_3' => array( 'Page text', 'Text 3: Consultancy', 'text', 'Consultancy' ),
	'legal_link_6_url' => array( 'Page text', 'Link 6 address', 'url', '/contact/' ),
);
