<?php
/**
 * Editable wording of the "events_archive" page: field => section, label, type, original wording.
 * Generated by tools/extract-page-text.py; labels and sections may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'archive_small_heading_1' => array( 'Past events', 'Label above heading 1: Past Events', 'text', 'Past Events' ),
	'archive_heading_1' => array( 'Past events', 'Heading 1: THE ARCHIVE', 'text', 'THE ARCHIVE' ),
	'archive_paragraph_1' => array( 'Past events', 'Text 1: Every night we have planned, booke...', 'text', 'Every night we have planned, booked and run, year by year.' ),
	'archive_text_1' => array( 'Past events', 'Text 1: APR', 'text', 'APR' ),
	'archive_small_heading_2' => array( 'Past events', 'Label above heading 2: Part 3', 'text', 'Part 3' ),
	'archive_heading_2' => array( 'Past events', 'Heading 2: Becoming Mr & Mrs Crux Pt.3', 'text', 'Becoming Mr & Mrs Crux Pt.3' ),
	'archive_paragraph_2' => array( 'Past events', 'Text 2: The third edition of our Becoming...', 'text', 'The third edition of our Becoming Mr & Mrs Crux celebration.' ),
	'archive_text_2' => array( 'Past events', 'Text 2: Details →', 'text', 'Details →' ),
	'archive_text_3' => array( 'Past events', 'Text 3: JAN', 'text', 'JAN' ),
	'archive_small_heading_3' => array( 'Past events', 'Label above heading 3: IJGB Edition', 'text', 'IJGB Edition' ),
	'archive_heading_3' => array( 'Past events', 'Heading 3: LASGIDI Mainland Party', 'text', 'LASGIDI Mainland Party' ),
	'archive_paragraph_3' => array( 'Past events', 'Text 3: The LASGIDI Mainland Party, IJGB e...', 'text', 'The LASGIDI Mainland Party, IJGB edition.' ),
	'archive_text_4' => array( 'Past events', 'Text 4: NOV', 'text', 'NOV' ),
	'archive_small_heading_4' => array( 'Past events', 'Label above heading 4: Culture', 'text', 'Culture' ),
	'archive_heading_4' => array( 'Past events', 'Heading 4: Ankara Festival', 'text', 'Ankara Festival' ),
	'archive_paragraph_4' => array( 'Past events', 'Text 4: The Ankara Festival celebrates the...', 'textarea', 'The Ankara Festival celebrates the vibrancy and diversity of African culture in the heart of the United Kingdom.' ),
	'archive_text_5' => array( 'Past events', 'Text 5: DEC', 'text', 'DEC' ),
	'archive_small_heading_5' => array( 'Past events', 'Label above heading 5: Dance night', 'text', 'Dance night' ),
	'archive_heading_5' => array( 'Past events', 'Heading 5: Dance OUT 2023', 'text', 'Dance OUT 2023' ),
	'archive_paragraph_5' => array( 'Past events', 'Text 5: Get ready to groove and move like...', 'textarea', 'Get ready to groove and move like never before. An electrifying night set to ignite the dance floor.' ),
	'archive_small_heading_6' => array( 'Past events', 'Label above heading 6: Awards', 'text', 'Awards' ),
	'archive_heading_6' => array( 'Past events', 'Heading 6: YAGI Awards', 'text', 'YAGI Awards' ),
	'archive_paragraph_6' => array( 'Past events', 'Text 6: Set to recognise individuals who h...', 'textarea', 'Set to recognise individuals who have done wonderfully well in their services and contributions to the community.' ),
	'archive_small_heading_7' => array( 'Past events', 'Label above heading 7: Games night', 'text', 'Games night' ),
	'archive_heading_7' => array( 'Past events', 'Heading 7: Millennials vs Gen Z', 'text', 'Millennials vs Gen Z' ),
	'archive_paragraph_7' => array( 'Past events', 'Text 7: Games night with Millennial crowds...', 'text', 'Games night with Millennial crowds taking on Gen Z to win ultimate bragging rights.' ),
	'archive_text_6' => array( 'Past events', 'Text 6: AUG', 'text', 'AUG' ),
	'archive_small_heading_8' => array( 'Past events', 'Label above heading 8: Wedding', 'text', 'Wedding' ),
	'archive_heading_8' => array( 'Past events', 'Heading 8: The Wedding Party', 'text', 'The Wedding Party' ),
	'archive_paragraph_8' => array( 'Past events', 'Text 8: Set up to celebrate the glamorous...', 'text', 'Set up to celebrate the glamorous Nigerian wedding party in the United Kingdom.' ),
	'archive_text_7' => array( 'Past events', 'Text 7: SEP', 'text', 'SEP' ),
	'archive_small_heading_9' => array( 'Past events', 'Label above heading 9: Social', 'text', 'Social' ),
	'archive_heading_9' => array( 'Past events', 'Heading 9: Crux Nxtion Hangout Out', 'text', 'Crux Nxtion Hangout Out' ),
	'archive_paragraph_9' => array( 'Past events', 'Text 9: An indoor games hangout: come soci...', 'text', 'An indoor games hangout: come socialise, make friends, network and vibe.' ),
	'archive_button_1' => array( 'Past events', 'Button 1: Book Your Own Night', 'text', 'Book Your Own Night' ),
	'archive_text_8' => array( 'Past events', 'Text 8: Events', 'text', 'Events' ),
	'archive_text_9' => array( 'Past events', 'Text 9: Consultancy', 'text', 'Consultancy' ),
	'archive_button_1_url' => array( 'Past events', 'Button 1 address', 'url', '/contact/' ),
);
