<?php
/**
 * Editable wording of the "events" page: field => section, label, type, original wording.
 * Generated by tools/extract-page-text.py; labels and sections may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'page_heading_small_heading_1' => array( 'Page heading', 'Label above heading 1: The Ticket Wall', 'text', 'The Ticket Wall' ),
	'page_heading_heading_1' => array( 'Page heading', 'Heading 1: EVENTS', 'text', 'EVENTS' ),
	'page_heading_paragraph_1' => array( 'Page heading', 'Text 1: Every ticket we\'ve printed, punche...', 'textarea', 'Every ticket we\'ve printed, punched by the same crew — weddings, dance nights, awards and festivals across the UK.' ),
	'ticket_grid_text_1' => array( 'Event list', 'Text 1: View Details →', 'text', 'View Details →' ),
	'ticket_grid_small_heading_1' => array( 'Event list', 'Label above heading 1: Your Night Next', 'text', 'Your Night Next' ),
	'ticket_grid_heading_1' => array( 'Event list', 'Heading 1: PUT YOUR EVENT ON THE WALL.', 'text', 'PUT YOUR EVENT ON THE WALL.' ),
	'ticket_grid_paragraph_1' => array( 'Event list', 'Text 1: Send us a brief and we will plan,...', 'text', 'Send us a brief and we will plan, book and run it.' ),
	'ticket_grid_button_1' => array( 'Event list', 'Button 1: Get In Touch', 'text', 'Get In Touch' ),
	'ticket_grid_text_2' => array( 'Event list', 'Text 2: Events', 'text', 'Events' ),
	'ticket_grid_text_3' => array( 'Event list', 'Text 3: Consultancy', 'text', 'Consultancy' ),
);
