<?php
/**
 * Editable wording of the "gallery" page: field => section, label, type, original wording.
 * Generated by tools/extract-page-text.py; labels and sections may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'page_heading_small_heading_1' => array( 'Page Heading', 'Page Heading: small heading 1 (The Ticket Wall)', 'text', 'The Ticket Wall' ),
	'page_heading_heading_1' => array( 'Page Heading', 'Page Heading: heading 1 (GALLERY)', 'text', 'GALLERY' ),
	'page_heading_paragraph_1' => array( 'Page Heading', 'Page Heading: paragraph 1 (Every frame, filed like a ticket —...)', 'text', 'Every frame, filed like a ticket — punched by the same crew.' ),
	'ticket_photo_grid_text_1' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 1 (WEDDING)', 'text', 'WEDDING' ),
	'ticket_photo_grid_text_2' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 2 (FRAME 01)', 'text', 'FRAME 01' ),
	'ticket_photo_grid_text_3' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 3 (NIGHT OUT)', 'text', 'NIGHT OUT' ),
	'ticket_photo_grid_text_4' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 4 (FRAME 02)', 'text', 'FRAME 02' ),
	'ticket_photo_grid_text_5' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 5 (LIVE)', 'text', 'LIVE' ),
	'ticket_photo_grid_text_6' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 6 (FRAME 03)', 'text', 'FRAME 03' ),
	'ticket_photo_grid_text_7' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 7 (CULTURE)', 'text', 'CULTURE' ),
	'ticket_photo_grid_text_8' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 8 (FRAME 04)', 'text', 'FRAME 04' ),
	'ticket_photo_grid_text_9' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 9 (CREW)', 'text', 'CREW' ),
	'ticket_photo_grid_text_10' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 10 (FRAME 05)', 'text', 'FRAME 05' ),
	'ticket_photo_grid_text_11' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 11 (PRIVATE)', 'text', 'PRIVATE' ),
	'ticket_photo_grid_text_12' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 12 (FRAME 06)', 'text', 'FRAME 06' ),
	'ticket_photo_grid_text_13' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 13 (FRAME 07)', 'text', 'FRAME 07' ),
	'ticket_photo_grid_text_14' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 14 (FRAME 08)', 'text', 'FRAME 08' ),
	'ticket_photo_grid_text_15' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 15 (FRAME 09)', 'text', 'FRAME 09' ),
	'ticket_photo_grid_text_16' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 16 (FRAME 10)', 'text', 'FRAME 10' ),
	'ticket_photo_grid_text_17' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 17 (FRAME 11)', 'text', 'FRAME 11' ),
	'ticket_photo_grid_text_18' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 18 (FRAME 12)', 'text', 'FRAME 12' ),
	'ticket_photo_grid_text_19' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 19 (FRAME 13)', 'text', 'FRAME 13' ),
	'ticket_photo_grid_text_20' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 20 (FRAME 14)', 'text', 'FRAME 14' ),
	'ticket_photo_grid_text_21' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 21 (FRAME 15)', 'text', 'FRAME 15' ),
	'ticket_photo_grid_text_22' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 22 (Events)', 'text', 'Events' ),
	'ticket_photo_grid_text_23' => array( 'Ticket Photo Grid', 'Ticket Photo Grid: text 23 (Consultancy)', 'text', 'Consultancy' ),
);
