<?php
/**
 * Editable wording of the "not_found" page: field => section, label, type, original wording.
 * Generated by tools/extract-page-text.py; labels and sections may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'page_small_heading_1' => array( 'Page text', 'Label above heading 1: Off The Guest List', 'text', 'Off The Guest List' ),
	'page_heading_1' => array( 'Page text', 'Heading 1: THIS PAGE DIDN\'T MAKE THE LINE-UP.', 'text', 'THIS PAGE DIDN\'T MAKE THE LINE-UP.' ),
	'page_paragraph_1' => array( 'Page text', 'Text 1: The link may be old, or the page h...', 'textarea', 'The link may be old, or the page has moved. Head back to the main room, or pick one of the doors below.' ),
	'page_button_1' => array( 'Page text', 'Button 1: Back To Home', 'text', 'Back To Home' ),
	'page_button_2' => array( 'Page text', 'Button 2: See Upcoming Events', 'text', 'See Upcoming Events' ),
	'page_heading_2' => array( 'Page text', 'Heading 2: Upcoming Events', 'text', 'Upcoming Events' ),
	'page_paragraph_2' => array( 'Page text', 'Text 2: See what is on the ticket wall.', 'text', 'See what is on the ticket wall.' ),
	'page_text_1' => array( 'Page text', 'Text 1: Take me there', 'text', 'Take me there' ),
	'page_heading_3' => array( 'Page text', 'Heading 3: Gallery', 'text', 'Gallery' ),
	'page_paragraph_3' => array( 'Page text', 'Text 3: Frames from nights we have run.', 'text', 'Frames from nights we have run.' ),
	'page_heading_4' => array( 'Page text', 'Heading 4: Our Services', 'text', 'Our Services' ),
	'page_paragraph_4' => array( 'Page text', 'Text 4: Events and consultancy, side by si...', 'text', 'Events and consultancy, side by side.' ),
	'page_heading_5' => array( 'Page text', 'Heading 5: Get In Touch', 'text', 'Get In Touch' ),
	'page_paragraph_5' => array( 'Page text', 'Text 5: Tell us the date, we will do the r...', 'text', 'Tell us the date, we will do the rest.' ),
	'page_text_2' => array( 'Page text', 'Text 2: Events', 'text', 'Events' ),
	'page_text_3' => array( 'Page text', 'Text 3: Consultancy', 'text', 'Consultancy' ),
	'page_button_1_url' => array( 'Page text', 'Button 1 address', 'url', '/' ),
	'page_button_2_url' => array( 'Page text', 'Button 2 address', 'url', '/events/' ),
);
