<?php
/**
 * Editable wording of the "privacy" page: field => section, label, type, original wording.
 * Generated by tools/extract-page-text.py; labels and sections may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'legal_small_heading_1' => array( 'Page text', 'Label above heading 1: Legal', 'text', 'Legal' ),
	'legal_heading_1' => array( 'Page text', 'Heading 1: PRIVACY POLICY', 'text', 'PRIVACY POLICY' ),
	'legal_paragraph_1' => array( 'Page text', 'Text 1: How Crux Nxtion Events collects, u...', 'textarea', 'How Crux Nxtion Events collects, uses and protects your personal information. We keep it plain and short.' ),
	'legal_paragraph_2' => array( 'Page text', 'Text 2: Last updated 19 September 2026', 'text', 'Last updated 19 September 2026' ),
	'legal_text_1' => array( 'Page text', 'Text 1: ON THIS PAGE', 'text', 'ON THIS PAGE' ),
	'legal_link_1' => array( 'Page text', 'Link 1: 1. Who we are', 'text', '1. Who we are' ),
	'legal_link_2' => array( 'Page text', 'Link 2: 2. What we collect', 'text', '2. What we collect' ),
	'legal_link_3' => array( 'Page text', 'Link 3: 3. How we use it', 'text', '3. How we use it' ),
	'legal_link_4' => array( 'Page text', 'Link 4: 4. Legal basis', 'text', '4. Legal basis' ),
	'legal_link_5' => array( 'Page text', 'Link 5: 5. Who we share it with', 'text', '5. Who we share it with' ),
	'legal_link_6' => array( 'Page text', 'Link 6: 6. How long we keep it', 'text', '6. How long we keep it' ),
	'legal_link_7' => array( 'Page text', 'Link 7: 7. Your rights', 'text', '7. Your rights' ),
	'legal_link_8' => array( 'Page text', 'Link 8: 8. Changes to this policy', 'text', '8. Changes to this policy' ),
	'legal_emphasis_1' => array( 'Page text', 'Highlighted words 1: Questions?', 'text', 'Questions?' ),
	'legal_paragraph_3' => array( 'Page text', 'Text 3: Email us and a real person will re...', 'text', 'Email us and a real person will reply.' ),
	'legal_link_9' => array( 'Page text', 'Link 9: Contact us →', 'text', 'Contact us →' ),
	'legal_paragraph_4' => array( 'Page text', 'Text 4: When you enquire, book or subscrib...', 'textarea', 'When you enquire, book or subscribe we collect your name, email address, phone number, the details of your event or business, and anything you choose to tell us.' ),
	'legal_paragraph_5' => array( 'Page text', 'Text 5: When you visit the website we coll...', 'textarea', 'When you visit the website we collect basic technical data such as your IP address, browser and pages visited, through cookies and similar tools (see our Cookie Policy).' ),
	'legal_paragraph_6' => array( 'Page text', 'Text 6: If you buy tickets for one of our...', 'textarea', 'If you buy tickets for one of our events through a third-party ticketing platform, that platform handles your payment details, not us.' ),
	'legal_paragraph_7' => array( 'Page text', 'Text 7: To reply to enquiries, plan and de...', 'text', 'To reply to enquiries, plan and deliver events, and provide consultancy services.' ),
	'legal_paragraph_8' => array( 'Page text', 'Text 8: To send updates you have asked for...', 'text', 'To send updates you have asked for. You can opt out at any time.' ),
	'legal_paragraph_9' => array( 'Page text', 'Text 9: To improve our website, to keep it...', 'text', 'To improve our website, to keep it secure and to meet legal obligations.' ),
	'legal_paragraph_10' => array( 'Page text', 'Text 10: We rely on contract (to deliver wh...', 'textarea', 'We rely on contract (to deliver what you have booked), legitimate interests (running and improving our business), consent (marketing and non-essential cookies) and legal obligation (for example, accounting records).' ),
	'legal_paragraph_11' => array( 'Page text', 'Text 11: Only people who help us deliver ou...', 'textarea', 'Only people who help us deliver our services: venues, suppliers, ticketing and payment platforms, website hosting, analytics and email providers. We do not sell your personal information.' ),
	'legal_paragraph_12' => array( 'Page text', 'Text 12: Enquiry and booking records are ke...', 'textarea', 'Enquiry and booking records are kept for as long as needed to deliver the service and for up to six years afterwards for accounting and legal reasons. Marketing contacts are kept until you unsubscribe.' ),
	'legal_paragraph_13' => array( 'Page text', 'Text 13: Under UK GDPR you can ask to see,...', 'textarea', 'Under UK GDPR you can ask to see, correct, delete or restrict the use of your information, object to certain uses, and request a copy of the data you gave us. You can also withdraw consent at any time.' ),
	'legal_paragraph_14' => array( 'Page text', 'Text 14: To use any of these rights, email', 'text', 'To use any of these rights, email' ),
	'legal_paragraph_15' => array( 'Page text', 'Text 15: . If you are unhappy with how we h...', 'textarea', '. If you are unhappy with how we handle your data you can complain to the Information Commissioner\'s Office at ico.org.uk.' ),
	'legal_paragraph_16' => array( 'Page text', 'Text 16: We may update this policy from tim...', 'textarea', 'We may update this policy from time to time. The date at the top shows when it last changed.' ),
	'legal_text_2' => array( 'Page text', 'Text 2: Events', 'text', 'Events' ),
	'legal_text_3' => array( 'Page text', 'Text 3: Consultancy', 'text', 'Consultancy' ),
	'legal_link_9_url' => array( 'Page text', 'Link 9 address', 'url', '/contact/' ),
);
