<?php
/**
 * Editable wording of the "single_event" page: field => section, label, type, original wording.
 * Generated by tools/extract-page-text.py; labels and sections may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'breadcrumb_link_1' => array( 'Breadcrumb', 'Link 1: Home', 'text', 'Home' ),
	'breadcrumb_link_2' => array( 'Breadcrumb', 'Link 2: Events', 'text', 'Events' ),
	'event_details_heading_1' => array( 'Event details', 'Heading 1: ABOUT THIS EVENT', 'text', 'ABOUT THIS EVENT' ),
	'event_details_heading_2' => array( 'Event details', 'Heading 2: From The Gallery', 'text', 'From The Gallery' ),
	'event_details_button_1' => array( 'Event details', 'Button 1: Reserve Your Spot', 'text', 'Reserve Your Spot' ),
	'event_details_button_2' => array( 'Event details', 'Button 2: Ask A Question', 'text', 'Ask A Question' ),
	'you_might_also_like_heading_1' => array( 'More events strip', 'Heading 1: YOU MIGHT ALSO LIKE', 'text', 'YOU MIGHT ALSO LIKE' ),
	'you_might_also_like_text_1' => array( 'More events strip', 'Text 1: Events', 'text', 'Events' ),
	'you_might_also_like_text_2' => array( 'More events strip', 'Text 2: Consultancy', 'text', 'Consultancy' ),
	'breadcrumb_link_1_url' => array( 'Breadcrumb', 'Link 1 address', 'url', '/' ),
	'breadcrumb_link_2_url' => array( 'Breadcrumb', 'Link 2 address', 'url', '/events/' ),
	'event_details_button_2_url' => array( 'Event details', 'Button 2 address', 'url', '/contact/' ),
);
