<?php
/**
 * Editable wording of the "single_post" page: field => section, label, type, original wording.
 * Generated by tools/extract-page-text.py; labels and sections may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'breadcrumb_link_1' => array( 'Breadcrumb', 'Link 1: Home', 'text', 'Home' ),
	'breadcrumb_link_2' => array( 'Breadcrumb', 'Link 2: Blog', 'text', 'Blog' ),
	'article_small_heading_1' => array( 'Article', 'Label above heading 1: Recent Posts', 'text', 'Recent Posts' ),
	'article_text_1' => array( 'Article', 'Text 1: Events', 'text', 'Events' ),
	'article_text_2' => array( 'Article', 'Text 2: Consultancy', 'text', 'Consultancy' ),
	'breadcrumb_link_1_url' => array( 'Breadcrumb', 'Link 1 address', 'url', '/' ),
	'breadcrumb_link_2_url' => array( 'Breadcrumb', 'Link 2 address', 'url', '/blog/' ),
);
