<?php
/**
 * Editable wording of the "sponsors" page: field => section, label, type, original wording.
 * Generated by tools/extract-page-text.py; labels and sections may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'sponsors_heading_small_heading_1' => array( 'Page heading', 'Label above heading 1: Sponsors & Partners', 'text', 'Sponsors & Partners' ),
	'sponsors_heading_heading_1' => array( 'Page heading', 'Heading 1: OUR SPONSORS AND PARTNERSHIP.', 'rich', 'OUR SPONSORS<br><span style="color:#E5383B;">AND PARTNERSHIP.</span>' ),
	'sponsors_heading_heading_2' => array( 'Page heading', 'Heading 2: Join the celebration: your gateway...', 'text', 'Join the celebration: your gateway to extraordinary partnerships with Crux Nxtion Events.' ),
	'sponsors_heading_paragraph_1' => array( 'Page heading', 'Text 1: Welcome to the heart of collaborat...', 'textarea', 'Welcome to the heart of collaboration. We are passionate about creating extraordinary experiences, and we believe in doing it together. Our partnership and vendors section is where connections spark, creativity thrives, and magic happens.' ),
	'sponsors_heading_button_1' => array( 'Page heading', 'Button 1: Become A Partner', 'text', 'Become A Partner' ),
	'sponsors_heading_button_2' => array( 'Page heading', 'Button 2: See Our Events', 'text', 'See Our Events' ),
	'partner_wall_small_heading_1' => array( 'Partner wall', 'Label above heading 1: Vendors & Partners', 'text', 'Vendors & Partners' ),
	'partner_wall_heading_1' => array( 'Partner wall', 'Heading 1: THE PEOPLE BEHIND THE NIGHT.', 'text', 'THE PEOPLE BEHIND THE NIGHT.' ),
	'partner_wall_paragraph_1' => array( 'Partner wall', 'Text 1: Caterers, photographers, DJs, beau...', 'text', 'Caterers, photographers, DJs, beauty and jewellery brands who have joined our events.' ),
	'partner_wall_text_1' => array( 'Partner wall', 'Text 1: Partner', 'text', 'Partner' ),
	'partner_wall_text_2' => array( 'Partner wall', 'Text 2: ML', 'text', 'ML' ),
	'partner_wall_text_3' => array( 'Partner wall', 'Text 3: Phemzy Studios', 'text', 'Phemzy Studios' ),
	'partner_wall_text_4' => array( 'Partner wall', 'Text 4: Dotun Omiyale', 'text', 'Dotun Omiyale' ),
	'partner_wall_text_5' => array( 'Partner wall', 'Text 5: DJ03', 'text', 'DJ03' ),
	'partner_wall_text_6' => array( 'Partner wall', 'Text 6: D20 Pasties', 'text', 'D20 Pasties' ),
	'partner_wall_text_7' => array( 'Partner wall', 'Text 7: Livingbangel Beauty Lounge', 'text', 'Livingbangel Beauty Lounge' ),
	'partner_wall_text_8' => array( 'Partner wall', 'Text 8: Food Emporium UK', 'text', 'Food Emporium UK' ),
	'partner_wall_text_9' => array( 'Partner wall', 'Text 9: Sokid Photography', 'text', 'Sokid Photography' ),
	'partner_wall_text_10' => array( 'Partner wall', 'Text 10: Zee Jewels', 'text', 'Zee Jewels' ),
	'partner_wall_text_11' => array( 'Partner wall', 'Text 11: Rosella\'s Wonder', 'text', 'Rosella\'s Wonder' ),
	'partner_wall_text_12' => array( 'Partner wall', 'Text 12: Events', 'text', 'Events' ),
	'partner_wall_text_13' => array( 'Partner wall', 'Text 13: Consultancy', 'text', 'Consultancy' ),
	'sponsors_heading_button_1_url' => array( 'Page heading', 'Button 1 address', 'url', '/contact/?type=partner' ),
	'sponsors_heading_button_2_url' => array( 'Page heading', 'Button 2 address', 'url', '/events/' ),
);
