<?php
/**
 * Editable wording of the "terms" page: field => section, label, type, original wording.
 * Generated by tools/extract-page-text.py; labels and sections may be edited by hand.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
return array(
	'legal_small_heading_1' => array( 'Page text', 'Label above heading 1: Legal', 'text', 'Legal' ),
	'legal_heading_1' => array( 'Page text', 'Heading 1: TERMS & CONDITIONS', 'text', 'TERMS & CONDITIONS' ),
	'legal_paragraph_1' => array( 'Page text', 'Text 1: The ground rules for using our web...', 'text', 'The ground rules for using our website and booking our services.' ),
	'legal_paragraph_2' => array( 'Page text', 'Text 2: Last updated 19 September 2026', 'text', 'Last updated 19 September 2026' ),
	'legal_text_1' => array( 'Page text', 'Text 1: ON THIS PAGE', 'text', 'ON THIS PAGE' ),
	'legal_link_1' => array( 'Page text', 'Link 1: 1. About these terms', 'text', '1. About these terms' ),
	'legal_link_2' => array( 'Page text', 'Link 2: 2. Event bookings and services', 'text', '2. Event bookings and services' ),
	'legal_link_3' => array( 'Page text', 'Link 3: 3. Tickets to our events', 'text', '3. Tickets to our events' ),
	'legal_link_4' => array( 'Page text', 'Link 4: 4. Photography and filming', 'text', '4. Photography and filming' ),
	'legal_link_5' => array( 'Page text', 'Link 5: 5. Our content', 'text', '5. Our content' ),
	'legal_link_6' => array( 'Page text', 'Link 6: 6. Liability', 'text', '6. Liability' ),
	'legal_link_7' => array( 'Page text', 'Link 7: 7. Governing law', 'text', '7. Governing law' ),
	'legal_link_8' => array( 'Page text', 'Link 8: 8. Contact', 'text', '8. Contact' ),
	'legal_emphasis_1' => array( 'Page text', 'Highlighted words 1: Questions?', 'text', 'Questions?' ),
	'legal_paragraph_3' => array( 'Page text', 'Text 3: Email us and a real person will re...', 'text', 'Email us and a real person will reply.' ),
	'legal_link_9' => array( 'Page text', 'Link 9: Contact us →', 'text', 'Contact us →' ),
	'legal_paragraph_4' => array( 'Page text', 'Text 4: A booking or consultancy engagemen...', 'textarea', 'A booking or consultancy engagement is only confirmed once we have agreed the scope, price and date in writing and any deposit has been received.' ),
	'legal_paragraph_5' => array( 'Page text', 'Text 5: Each booking is covered by a writt...', 'textarea', 'Each booking is covered by a written proposal or agreement that sets out deposits, payment dates, changes and cancellation. Where that document differs from these terms, the document applies.' ),
	'legal_paragraph_6' => array( 'Page text', 'Text 6: Tickets are sold through third-par...', 'textarea', 'Tickets are sold through third-party platforms and are subject to their terms as well as any event-specific conditions on the ticket page. Age limits and venue rules apply and entry may be refused where they are not met.' ),
	'legal_paragraph_7' => array( 'Page text', 'Text 7: We photograph and film at our even...', 'textarea', 'We photograph and film at our events for marketing and to share memories. Notices will be displayed at the venue. If you would rather not appear, please tell a member of the crew.' ),
	'legal_paragraph_8' => array( 'Page text', 'Text 8: All text, images, logos and design...', 'textarea', 'All text, images, logos and designs on this website belong to Crux Nxtion Events or its licensors. You may not copy or reuse them without written permission.' ),
	'legal_paragraph_9' => array( 'Page text', 'Text 9: We take care to keep the website a...', 'textarea', 'We take care to keep the website accurate but provide it as is. Nothing in these terms limits liability that cannot lawfully be limited, including for death or personal injury caused by negligence or for fraud.' ),
	'legal_paragraph_10' => array( 'Page text', 'Text 10: These terms are governed by the la...', 'textarea', 'These terms are governed by the laws of England and Wales and disputes are subject to the courts of England and Wales.' ),
	'legal_paragraph_11' => array( 'Page text', 'Text 11: Email', 'text', 'Email' ),
	'legal_paragraph_12' => array( 'Page text', 'Text 12: with any questions about these ter...', 'text', 'with any questions about these terms.' ),
	'legal_text_2' => array( 'Page text', 'Text 2: Events', 'text', 'Events' ),
	'legal_text_3' => array( 'Page text', 'Text 3: Consultancy', 'text', 'Consultancy' ),
	'legal_link_9_url' => array( 'Page text', 'Link 9 address', 'url', '/contact/' ),
);
