"""Customizer phase C3: make the photos of a page template replaceable.

  python tools/extract-page-images.py <template.php> <page-key> [--write]

Finds every  crux_get_blob_url( '<32 hex>' )  in the template (the design's photos), gives each distinct photo in a
page region a media field whose default is that same photo, and replaces the call with

    crux_img_url( '<page-key>', '<field>' )

which prints the Media Library picture the client chose, or the original photo when nothing was chosen.
Writes cruxnxtion-theme/inc/content/images/<page-key>.php  (field => region, label, 'media', original photo id).
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
THEME = os.path.join(ROOT, 'cruxnxtion-theme')
CALL = re.compile(r"crux_get_blob_url\(\s*(['\"])([0-9a-f]{32})\1\s*\)")
CMT = re.compile(r'<!--(.*?)-->', re.S)


def slug(s):
    s = re.sub(r'[^a-z0-9]+', '_', s.lower()).strip('_')
    return s[:28] or 'page'


def section_title(c):
    c = re.sub(r'^[\d#.\s]+', '', c.strip())
    c = re.split(r'\s+[—–-]\s+|\(|:', c)[0].strip()
    return c.title() if c.isupper() or c.islower() else c


def resolve(path):
    return path if os.path.isabs(path) or os.path.exists(path) else os.path.join(THEME, path)


def main():
    path, page = sys.argv[1], sys.argv[2]
    write = '--write' in sys.argv
    raw = open(resolve(path), encoding='utf-8', newline='').read()
    crlf = '\r\n' in raw
    src = raw.replace('\r\n', '\n')
    body_start = src.find('<body')
    head, body = src[:body_start], src[body_start:]

    # Region comments with their positions.
    regions = []
    for m in CMT.finditer(body):
        line_start = body[:m.start()].rsplit('\n', 1)[-1]
        if line_start.strip() == '' and len(line_start) <= 4:
            t = section_title(m.group(1))
            if t:
                regions.append((m.start(), t))

    def region_at(pos):
        r = 'Page'
        for p, t in regions:
            if p <= pos:
                r = t
        return r

    fields = []
    counters = {}
    seen = {}
    out = []
    last = 0
    for m in CALL.finditer(body):
        sec = region_at(m.start())
        h = m.group(2)
        k = (sec, h)
        if k not in seen:
            counters[sec] = counters.get(sec, 0) + 1
            n = counters[sec]
            key = slug(sec) + '_photo_' + str(n)
            seen[k] = key
            alt = re.search(r'alt\s*=\s*"([^"<>]{3,60})"', body[m.end():m.end() + 400])
            hint = (' (' + alt.group(1) + ')') if alt else ''
            fields.append((key, sec, '%s: photo %d%s' % (sec, n, hint), h))
        out.append(body[last:m.start()])
        out.append("crux_img_url( '%s', '%s' )" % (page, seen[k]))
        last = m.end()
    out.append(body[last:])
    new_src = head + ''.join(out)

    print('%s: %d photos in %d regions' % (path, len(fields), len(counters)))
    for f in fields:
        print('   %-30s %s' % (f[0], f[2]))
    if not write or not fields:
        return

    def q(s):
        return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"
    lines = ['<?php', '/**', ' * Replaceable photos of the "%s" page: field => region, label, type, original photo id.' % page,
             ' * Generated by tools/extract-page-images.py; labels may be edited by hand.', ' */', "if ( ! defined( 'ABSPATH' ) ) {", '\texit;', '}', 'return array(']
    for key, sec, label, h in fields:
        lines.append("\t%s => array( %s, %s, 'media', %s )," % (q(key), q(sec), q(label), q(h)))
    lines.append(');')
    os.makedirs(os.path.join(THEME, 'inc', 'content', 'images'), exist_ok=True)
    open(os.path.join(THEME, 'inc', 'content', 'images', page + '.php'), 'w', encoding='utf-8', newline='').write('\n'.join(lines) + '\n')
    open(resolve(path), 'w', encoding='utf-8', newline='').write(new_src.replace('\n', '\r\n') if crlf else new_src)
    print('written')


main()
