"""Customizer phase C4: mark the page elements that belong to a Customizer field.

  python tools/mark-editable.py <template.php> <page-key> [--write]

For every element whose only content is a crux_h()/crux_rich() call, and every tag that prints a crux_img_url()
photo, adds  <?php echo crux_edit_attr( 'page', 'key' ); ?>  inside the opening tag. On the public site that prints
nothing; inside the Customizer preview it prints data-crux-edit="page.key", which is what lets the preview show a
pencil that jumps to the field and update plain text as it is typed.

Also (re)writes cruxnxtion-theme/inc/content/live.php, the list of text fields that can update instantly.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
THEME = os.path.join(ROOT, 'cruxnxtion-theme')
PHP_RE = re.compile(r'<\?(?:php|=).*?\?>', re.S)
PH_O, PH_C = '', ''
TEXT_CALL = re.compile(r"^\s*((\d+))\s*$")


def main():
    path, page = sys.argv[1], sys.argv[2]
    write = '--write' in sys.argv
    full = os.path.join(THEME, path)
    raw = open(full, encoding='utf-8', newline='').read()
    crlf = '\r\n' in raw
    src = raw.replace('\r\n', '\n')
    start = src.find('<body')
    head, body = src[:start], src[start:]
    php = []

    def hide(m):
        php.append(m.group(0))
        return PH_O + str(len(php) - 1) + PH_C
    body = PHP_RE.sub(hide, body)

    CALL = re.compile(r"crux_(h|rich)\(\s*'%s',\s*'(\w+)'\s*\)" % re.escape(page))
    IMG = re.compile(r"crux_img_url\(\s*'%s',\s*'(\w+)'\s*\)" % re.escape(page))
    marked_text, marked_img = [], []

    # 1. elements whose only content is one text call
    def mark_text(m):
        open_tag, name, inner, close = m.group(1), m.group(2), m.group(3), m.group(4)
        tm = TEXT_CALL.match(inner)
        if not tm or 'data-crux-edit' in open_tag or PH_O in open_tag and 'crux_edit_attr' in php[int(re.findall('(\d+)', open_tag)[-1])]:
            return m.group(0)
        cm = CALL.search(php[int(tm.group(2))])
        if not cm:
            return m.group(0)
        php.append("<?php echo crux_edit_attr( '%s', '%s' ); ?>" % (page, cm.group(2)))
        marked_text.append((cm.group(1), cm.group(2)))
        return open_tag[:-1] + PH_O + str(len(php) - 1) + PH_C + '>' + inner + close
    body = re.sub(r'(<([a-zA-Z][a-zA-Z0-9]*)\b[^<>]*>)([^<>]*)(</\2\s*>)', mark_text, body)

    # 2. tags that print a photo
    def mark_img(m):
        tag = m.group(0)
        if 'crux_edit_attr' in ''.join(php[int(i)] for i in re.findall('(\d+)', tag)):
            return tag
        for i in re.findall('(\d+)', tag):
            im = IMG.search(php[int(i)])
            if im:
                php.append("<?php echo crux_edit_attr( '%s', '%s' ); ?>" % (page, im.group(1)))
                marked_img.append(im.group(1))
                end = '/>' if tag.endswith('/>') else '>'
                return tag[:-len(end)].rstrip() + PH_O + str(len(php) - 1) + PH_C + end if False else tag[:-len(end)] + PH_O + str(len(php) - 1) + PH_C + end
        return tag
    body = re.sub(r'<[a-zA-Z][^<>]*>', mark_img, body)

    for i in range(len(php) - 1, -1, -1):
        body = body.replace(PH_O + str(i) + PH_C, php[i])
    new = head + body
    print('%s: %d text elements, %d photo tags marked' % (path, len(marked_text), len(marked_img)))
    if not write:
        return
    open(full, 'w', encoding='utf-8', newline='').write(new.replace('\n', '\r\n') if crlf else new)
    live = os.path.join(THEME, 'inc', 'content', 'live', page + '.php')
    os.makedirs(os.path.dirname(live), exist_ok=True)
    keys = sorted({k for fn, k in marked_text if fn == 'h'})
    open(live, 'w', encoding='utf-8', newline='').write(
        "<?php\n/** Text fields of the \"%s\" page that update instantly in the Customizer preview. Generated by tools/mark-editable.py. */\nif ( ! defined( 'ABSPATH' ) ) {\n\texit;\n}\nreturn array(\n%s);\n" % (page, ''.join("\t'%s',\n" % k for k in keys)))


main()
