<?php
/**
 * Template Name: Crux Nxtion - Template
 *
 * @package CruxNxtion
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<?php crux_use_page_css( 'dark' ); get_header( null, array( 'body_bg' => 'var(--crux-ink,#0A0F26)', 'root_bg' => 'var(--crux-ink,#0A0F26)', 'skin' => 'dark', 'nav' => 'events', 'wing' => 'events', 'active' => '' ) ); ?>

  <!-- SPONSORS HEADING -->
  <section style=" padding:44px 20px 40px 20px; display:grid; grid-template-columns:1.15fr .85fr; gap:56px; align-items:center;" data-m="g1">
    <div><span class="eyebrow"<?php echo crux_edit_attr( 'sponsors', 'sponsors_heading_small_heading_1' ); ?>><?php echo crux_h( 'sponsors', 'sponsors_heading_small_heading_1' ); ?></span>
    <h1 class="bebas" style="font-size:44px; margin:14px 0px 16px 0px; color:var(--crux-text,#F4F5FA);"<?php echo crux_edit_attr( 'sponsors', 'sponsors_heading_heading_1' ); ?>><?php echo crux_rich( 'sponsors', 'sponsors_heading_heading_1' ); ?></h1>
    <h2 style="font-size:19px; line-height:1.4; font-weight:700; margin:0px 0px 14px 0px; color:var(--crux-text,#F4F5FA); max-width:560px;"<?php echo crux_edit_attr( 'sponsors', 'sponsors_heading_heading_2' ); ?>><?php echo crux_h( 'sponsors', 'sponsors_heading_heading_2' ); ?></h2>
    <p style="font-size:15.5px; line-height:1.7; color:#A3A9C8; max-width:560px; margin:0px 0px 26px 0px;"<?php echo crux_edit_attr( 'sponsors', 'sponsors_heading_paragraph_1' ); ?>><?php echo crux_h( 'sponsors', 'sponsors_heading_paragraph_1' ); ?></p>
    <div style="display:flex; gap:16px;"><a href="<?php echo crux_url( 'sponsors', 'sponsors_heading_button_1_url' ); ?>" style="background:var(--crux-red,#BA0000); color:#FFFFFF; font-weight:700; font-size:15px; padding:16px 30px 16px 30px; --sl:10px;" class="bx"<?php echo crux_edit_attr( 'sponsors', 'sponsors_heading_button_1' ); ?>><?php echo crux_h( 'sponsors', 'sponsors_heading_button_1' ); ?></a><a href="<?php echo crux_url( 'sponsors', 'sponsors_heading_button_2_url' ); ?>" style="color:var(--crux-text,#F4F5FA); font-weight:700; font-size:15px; padding:14px 28px 14px 28px; --sl:10px; --bc:var(--crux-blue,#5B8DEF);" class="bx"<?php echo crux_edit_attr( 'sponsors', 'sponsors_heading_button_2' ); ?>><?php echo crux_h( 'sponsors', 'sponsors_heading_button_2' ); ?></a></div></div>
    <div style="position:relative; height:440px; border-radius:16px; overflow:hidden; border:1.5px solid var(--crux-line,#1E2B5E);"><img src="<?php echo crux_img_url( 'sponsors', 'sponsors_heading_photo_1' ); ?>" alt="Vendors serving guests at a Crux Nxtion event" style="width:100%; height:100%; object-fit:cover;"<?php echo crux_edit_attr( 'sponsors', 'sponsors_heading_photo_1' ); ?>><div style="position:absolute; inset:0; background:linear-gradient(0deg,rgba(10,15,38,.7),rgba(10,15,38,0) 55%);"></div></div>
  </section>

  <!-- PARTNER WALL -->
  <section style=" padding:50px 20px 44px 20px;">
    <div style="display:flex; justify-content:space-between; align-items:flex-end; margin-bottom:30px;" data-m="stack"><div><span class="eyebrow"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_small_heading_1' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_small_heading_1' ); ?></span><h2 class="bebas" style="font-size:34px; margin:12px 0px 0px 0px; color:var(--crux-text,#F4F5FA);"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_heading_1' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_heading_1' ); ?></h2></div><p style="max-width:380px; font-size:14px; line-height:1.6; color:#A3A9C8; margin:0px 0px 0px 0px;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_paragraph_1' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_paragraph_1' ); ?></p></div>
    <div style="display:grid; grid-template-columns:repeat(4, minmax(0, 1fr)); gap:26px 22px; align-items:start;" data-m="g2">
      <div style="display:flex; flex-direction:column; background:var(--crux-surface,#111838); border:1.5px solid var(--crux-line,#1E2B5E); border-radius:12px; overflow:hidden; transform:rotate(-1deg);">
        <div style="position:relative; aspect-ratio:1/1; background:var(--crux-text,#F4F5FA);"><img src="<?php echo crux_img_url( 'sponsors', 'partner_wall_photo_1' ); ?>" alt="Crux Nxtion partner" style="width:100%; height:100%; object-fit:cover; display:block;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_photo_1' ); ?>></div>
        <div class="strip-stub" style="background:var(--crux-navy,#002671); padding:11px 16px 11px 16px; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:11.5px; font-weight:800; color:#FFFFFF; letter-spacing:.8px; text-transform:uppercase;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_text_1' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_text_1' ); ?></span><span class="bebas" style="font-size:14px; color:#FFFFFF;">01</span></div>
      </div>
      <div style="display:flex; flex-direction:column; background:var(--crux-surface,#111838); border:1.5px solid var(--crux-line,#1E2B5E); border-radius:12px; overflow:hidden; transform:rotate(0.8deg);">
        <div style="position:relative; aspect-ratio:1/1; background:var(--crux-text,#F4F5FA);"><img src="<?php echo crux_img_url( 'sponsors', 'partner_wall_photo_2' ); ?>" alt="Crux Nxtion partner" style="width:100%; height:100%; object-fit:cover; display:block;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_photo_2' ); ?>></div>
        <div class="strip-stub" style="background:var(--crux-red,#BA0000); padding:11px 16px 11px 16px; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:11.5px; font-weight:800; color:#FFFFFF; letter-spacing:.8px; text-transform:uppercase;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_text_1' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_text_1' ); ?></span><span class="bebas" style="font-size:14px; color:#FFFFFF;">02</span></div>
      </div>
      <div style="display:flex; flex-direction:column; background:var(--crux-surface,#111838); border:1.5px solid var(--crux-line,#1E2B5E); border-radius:12px; overflow:hidden; transform:rotate(-0.6deg);">
        <div style="position:relative; aspect-ratio:1/1; background:var(--crux-text,#F4F5FA);"><img src="<?php echo crux_img_url( 'sponsors', 'partner_wall_photo_3' ); ?>" alt="ML" style="width:100%; height:100%; object-fit:cover; display:block;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_photo_3' ); ?>></div>
        <div class="strip-stub" style="background:var(--crux-purple,#8C7AE6); padding:11px 16px 11px 16px; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:11.5px; font-weight:800; color:var(--crux-ink2,#10142E); letter-spacing:.8px; text-transform:uppercase;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_text_2' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_text_2' ); ?></span><span class="bebas" style="font-size:14px; color:var(--crux-ink2,#10142E);">03</span></div>
      </div>
      <div style="display:flex; flex-direction:column; background:var(--crux-surface,#111838); border:1.5px solid var(--crux-line,#1E2B5E); border-radius:12px; overflow:hidden; transform:rotate(1deg);">
        <div style="position:relative; aspect-ratio:1/1; background:var(--crux-text,#F4F5FA);"><img src="<?php echo crux_img_url( 'sponsors', 'partner_wall_photo_4' ); ?>" alt="Phemzy Studios" style="width:100%; height:100%; object-fit:cover; display:block;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_photo_4' ); ?>></div>
        <div class="strip-stub" style="background:var(--crux-navy,#002671); padding:11px 16px 11px 16px; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:11.5px; font-weight:800; color:#FFFFFF; letter-spacing:.8px; text-transform:uppercase;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_text_3' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_text_3' ); ?></span><span class="bebas" style="font-size:14px; color:#FFFFFF;">04</span></div>
      </div>
      <div style="display:flex; flex-direction:column; background:var(--crux-surface,#111838); border:1.5px solid var(--crux-line,#1E2B5E); border-radius:12px; overflow:hidden; transform:rotate(-1deg);">
        <div style="position:relative; aspect-ratio:1/1; background:var(--crux-text,#F4F5FA);"><img src="<?php echo crux_img_url( 'sponsors', 'partner_wall_photo_5' ); ?>" alt="Crux Nxtion partner" style="width:100%; height:100%; object-fit:cover; display:block;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_photo_5' ); ?>></div>
        <div class="strip-stub" style="background:var(--crux-red,#BA0000); padding:11px 16px 11px 16px; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:11.5px; font-weight:800; color:#FFFFFF; letter-spacing:.8px; text-transform:uppercase;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_text_1' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_text_1' ); ?></span><span class="bebas" style="font-size:14px; color:#FFFFFF;">05</span></div>
      </div>
      <div style="display:flex; flex-direction:column; background:var(--crux-surface,#111838); border:1.5px solid var(--crux-line,#1E2B5E); border-radius:12px; overflow:hidden; transform:rotate(0.8deg);">
        <div style="position:relative; aspect-ratio:1/1; background:var(--crux-text,#F4F5FA);"><img src="<?php echo crux_img_url( 'sponsors', 'partner_wall_photo_6' ); ?>" alt="Dotun Omiyale" style="width:100%; height:100%; object-fit:cover; display:block;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_photo_6' ); ?>></div>
        <div class="strip-stub" style="background:var(--crux-purple,#8C7AE6); padding:11px 16px 11px 16px; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:11.5px; font-weight:800; color:var(--crux-ink2,#10142E); letter-spacing:.8px; text-transform:uppercase;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_text_4' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_text_4' ); ?></span><span class="bebas" style="font-size:14px; color:var(--crux-ink2,#10142E);">06</span></div>
      </div>
      <div style="display:flex; flex-direction:column; background:var(--crux-surface,#111838); border:1.5px solid var(--crux-line,#1E2B5E); border-radius:12px; overflow:hidden; transform:rotate(-0.6deg);">
        <div style="position:relative; aspect-ratio:1/1; background:var(--crux-text,#F4F5FA);"><img src="<?php echo crux_img_url( 'sponsors', 'partner_wall_photo_7' ); ?>" alt="Crux Nxtion partner" style="width:100%; height:100%; object-fit:cover; display:block;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_photo_7' ); ?>></div>
        <div class="strip-stub" style="background:var(--crux-navy,#002671); padding:11px 16px 11px 16px; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:11.5px; font-weight:800; color:#FFFFFF; letter-spacing:.8px; text-transform:uppercase;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_text_1' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_text_1' ); ?></span><span class="bebas" style="font-size:14px; color:#FFFFFF;">07</span></div>
      </div>
      <div style="display:flex; flex-direction:column; background:var(--crux-surface,#111838); border:1.5px solid var(--crux-line,#1E2B5E); border-radius:12px; overflow:hidden; transform:rotate(1deg);">
        <div style="position:relative; aspect-ratio:1/1; background:var(--crux-text,#F4F5FA);"><img src="<?php echo crux_img_url( 'sponsors', 'partner_wall_photo_8' ); ?>" alt="DJ03" style="width:100%; height:100%; object-fit:cover; display:block;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_photo_8' ); ?>></div>
        <div class="strip-stub" style="background:var(--crux-red,#BA0000); padding:11px 16px 11px 16px; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:11.5px; font-weight:800; color:#FFFFFF; letter-spacing:.8px; text-transform:uppercase;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_text_5' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_text_5' ); ?></span><span class="bebas" style="font-size:14px; color:#FFFFFF;">08</span></div>
      </div>
      <div style="display:flex; flex-direction:column; background:var(--crux-surface,#111838); border:1.5px solid var(--crux-line,#1E2B5E); border-radius:12px; overflow:hidden; transform:rotate(-1deg);">
        <div style="position:relative; aspect-ratio:1/1; background:var(--crux-text,#F4F5FA);"><img src="<?php echo crux_img_url( 'sponsors', 'partner_wall_photo_9' ); ?>" alt="Crux Nxtion partner" style="width:100%; height:100%; object-fit:cover; display:block;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_photo_9' ); ?>></div>
        <div class="strip-stub" style="background:var(--crux-purple,#8C7AE6); padding:11px 16px 11px 16px; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:11.5px; font-weight:800; color:var(--crux-ink2,#10142E); letter-spacing:.8px; text-transform:uppercase;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_text_1' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_text_1' ); ?></span><span class="bebas" style="font-size:14px; color:var(--crux-ink2,#10142E);">09</span></div>
      </div>
      <div style="display:flex; flex-direction:column; background:var(--crux-surface,#111838); border:1.5px solid var(--crux-line,#1E2B5E); border-radius:12px; overflow:hidden; transform:rotate(0.8deg);">
        <div style="position:relative; aspect-ratio:1/1; background:var(--crux-text,#F4F5FA);"><img src="<?php echo crux_img_url( 'sponsors', 'partner_wall_photo_10' ); ?>" alt="D20 Pasties" style="width:100%; height:100%; object-fit:cover; display:block;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_photo_10' ); ?>></div>
        <div class="strip-stub" style="background:var(--crux-navy,#002671); padding:11px 16px 11px 16px; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:11.5px; font-weight:800; color:#FFFFFF; letter-spacing:.8px; text-transform:uppercase;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_text_6' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_text_6' ); ?></span><span class="bebas" style="font-size:14px; color:#FFFFFF;">10</span></div>
      </div>
      <div style="display:flex; flex-direction:column; background:var(--crux-surface,#111838); border:1.5px solid var(--crux-line,#1E2B5E); border-radius:12px; overflow:hidden; transform:rotate(-0.6deg);">
        <div style="position:relative; aspect-ratio:1/1; background:var(--crux-text,#F4F5FA);"><img src="<?php echo crux_img_url( 'sponsors', 'partner_wall_photo_11' ); ?>" alt="Livingbangel Beauty Lounge" style="width:100%; height:100%; object-fit:cover; display:block;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_photo_11' ); ?>></div>
        <div class="strip-stub" style="background:var(--crux-red,#BA0000); padding:11px 16px 11px 16px; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:11.5px; font-weight:800; color:#FFFFFF; letter-spacing:.8px; text-transform:uppercase;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_text_7' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_text_7' ); ?></span><span class="bebas" style="font-size:14px; color:#FFFFFF;">11</span></div>
      </div>
      <div style="display:flex; flex-direction:column; background:var(--crux-surface,#111838); border:1.5px solid var(--crux-line,#1E2B5E); border-radius:12px; overflow:hidden; transform:rotate(1deg);">
        <div style="position:relative; aspect-ratio:1/1; background:var(--crux-text,#F4F5FA);"><img src="<?php echo crux_img_url( 'sponsors', 'partner_wall_photo_12' ); ?>" alt="Food Emporium UK" style="width:100%; height:100%; object-fit:cover; display:block;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_photo_12' ); ?>></div>
        <div class="strip-stub" style="background:var(--crux-purple,#8C7AE6); padding:11px 16px 11px 16px; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:11.5px; font-weight:800; color:var(--crux-ink2,#10142E); letter-spacing:.8px; text-transform:uppercase;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_text_8' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_text_8' ); ?></span><span class="bebas" style="font-size:14px; color:var(--crux-ink2,#10142E);">12</span></div>
      </div>
      <div style="display:flex; flex-direction:column; background:var(--crux-surface,#111838); border:1.5px solid var(--crux-line,#1E2B5E); border-radius:12px; overflow:hidden; transform:rotate(-1deg);">
        <div style="position:relative; aspect-ratio:1/1; background:var(--crux-text,#F4F5FA);"><img src="<?php echo crux_img_url( 'sponsors', 'partner_wall_photo_13' ); ?>" alt="Crux Nxtion partner" style="width:100%; height:100%; object-fit:cover; display:block;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_photo_13' ); ?>></div>
        <div class="strip-stub" style="background:var(--crux-navy,#002671); padding:11px 16px 11px 16px; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:11.5px; font-weight:800; color:#FFFFFF; letter-spacing:.8px; text-transform:uppercase;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_text_1' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_text_1' ); ?></span><span class="bebas" style="font-size:14px; color:#FFFFFF;">13</span></div>
      </div>
      <div style="display:flex; flex-direction:column; background:var(--crux-surface,#111838); border:1.5px solid var(--crux-line,#1E2B5E); border-radius:12px; overflow:hidden; transform:rotate(0.8deg);">
        <div style="position:relative; aspect-ratio:1/1; background:var(--crux-text,#F4F5FA);"><img src="<?php echo crux_img_url( 'sponsors', 'partner_wall_photo_14' ); ?>" alt="Crux Nxtion partner" style="width:100%; height:100%; object-fit:cover; display:block;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_photo_14' ); ?>></div>
        <div class="strip-stub" style="background:var(--crux-red,#BA0000); padding:11px 16px 11px 16px; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:11.5px; font-weight:800; color:#FFFFFF; letter-spacing:.8px; text-transform:uppercase;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_text_1' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_text_1' ); ?></span><span class="bebas" style="font-size:14px; color:#FFFFFF;">14</span></div>
      </div>
      <div style="display:flex; flex-direction:column; background:var(--crux-surface,#111838); border:1.5px solid var(--crux-line,#1E2B5E); border-radius:12px; overflow:hidden; transform:rotate(-0.6deg);">
        <div style="position:relative; aspect-ratio:1/1; background:var(--crux-text,#F4F5FA);"><img src="<?php echo crux_img_url( 'sponsors', 'partner_wall_photo_15' ); ?>" alt="Sokid Photography" style="width:100%; height:100%; object-fit:cover; display:block;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_photo_15' ); ?>></div>
        <div class="strip-stub" style="background:var(--crux-purple,#8C7AE6); padding:11px 16px 11px 16px; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:11.5px; font-weight:800; color:var(--crux-ink2,#10142E); letter-spacing:.8px; text-transform:uppercase;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_text_9' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_text_9' ); ?></span><span class="bebas" style="font-size:14px; color:var(--crux-ink2,#10142E);">15</span></div>
      </div>
      <div style="display:flex; flex-direction:column; background:var(--crux-surface,#111838); border:1.5px solid var(--crux-line,#1E2B5E); border-radius:12px; overflow:hidden; transform:rotate(1deg);">
        <div style="position:relative; aspect-ratio:1/1; background:var(--crux-text,#F4F5FA);"><img src="<?php echo crux_img_url( 'sponsors', 'partner_wall_photo_16' ); ?>" alt="Zee Jewels" style="width:100%; height:100%; object-fit:cover; display:block;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_photo_16' ); ?>></div>
        <div class="strip-stub" style="background:var(--crux-navy,#002671); padding:11px 16px 11px 16px; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:11.5px; font-weight:800; color:#FFFFFF; letter-spacing:.8px; text-transform:uppercase;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_text_10' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_text_10' ); ?></span><span class="bebas" style="font-size:14px; color:#FFFFFF;">16</span></div>
      </div>
      <div style="display:flex; flex-direction:column; background:var(--crux-surface,#111838); border:1.5px solid var(--crux-line,#1E2B5E); border-radius:12px; overflow:hidden; transform:rotate(-1deg);">
        <div style="position:relative; aspect-ratio:1/1; background:var(--crux-text,#F4F5FA);"><img src="<?php echo crux_img_url( 'sponsors', 'partner_wall_photo_17' ); ?>" alt="Rosella's Wonder" style="width:100%; height:100%; object-fit:cover; display:block;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_photo_17' ); ?>></div>
        <div class="strip-stub" style="background:var(--crux-red,#BA0000); padding:11px 16px 11px 16px; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:11.5px; font-weight:800; color:#FFFFFF; letter-spacing:.8px; text-transform:uppercase;"<?php echo crux_edit_attr( 'sponsors', 'partner_wall_text_11' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_text_11' ); ?></span><span class="bebas" style="font-size:14px; color:#FFFFFF;">17</span></div>
      </div>
    </div>
  </section>

  <?php get_template_part( 'parts/site-footer', null, array( 'skin' => 'dark', 'prefooter' => 'events', 'wing' => 'events' ) ); ?>

<div class="msw">
  <div class="crux-sw-pod crux-sw-pod--dark" style="pointer-events:auto; display:inline-flex; align-items:center; padding:1.5px; background:linear-gradient(135deg, #2A3F7A 0%, #15224A 100%); clip-path:polygon(8px 0, 100% 0, calc(100% - 8px) 100%, 0 100%); box-shadow:0 14px 36px rgba(0,0,0,0.65); filter:drop-shadow(0 4px 12px rgba(0,0,0,0.4));">
    <div class="crux-sw-inner" style="display:inline-flex; align-items:center; background:#020512; padding:4px; gap:4px; clip-path:polygon(7px 0, 100% 0, calc(100% - 7px) 100%, 0 100%);">
      <a href="<?php echo esc_url( home_url( "/" ) ); ?>" class="crux-sw-tab crux-sw-tab--active-events" style="display:inline-flex; align-items:center; justify-content:center; padding:11px 22px; min-width:140px; font-size:13px; font-weight:700; letter-spacing:0.3px; text-transform:uppercase; text-decoration:none; line-height:1.2; background:#1E48B0; color:#FFFFFF; clip-path:polygon(6px 0, 100% 0, calc(100% - 6px) 100%, 0 100%); box-shadow:0 2px 8px rgba(30,72,176,0.5);">
        <span<?php echo crux_edit_attr( 'sponsors', 'partner_wall_text_12' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_text_12' ); ?></span>
      </a>
      <a href="<?php echo esc_url( home_url( "/consultancy/" ) ); ?>" class="crux-sw-tab crux-sw-tab--inactive-dark" style="display:inline-flex; align-items:center; justify-content:center; padding:11px 22px; min-width:140px; font-size:13px; font-weight:600; letter-spacing:0.3px; text-transform:uppercase; text-decoration:none; line-height:1.2; background:transparent; color:#8E96BB; clip-path:polygon(6px 0, 100% 0, calc(100% - 6px) 100%, 0 100%); transition:all .2s ease;">
        <span<?php echo crux_edit_attr( 'sponsors', 'partner_wall_text_13' ); ?>><?php echo crux_h( 'sponsors', 'partner_wall_text_13' ); ?></span><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" style="margin-left:6px; display:inline-block; vertical-align:middle;"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>
      </a>
    </div>
  </div>
</div></div></div>





<?php get_footer(); ?>
