<?php
/**
 * Template Name: Crux Nxtion - Template
 *
 * @package CruxNxtion
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<?php crux_use_page_css( 'faq' ); get_header( null, array( 'body_bg' => '#FFFFFF', 'root_bg' => '#FFFFFF', 'skin' => 'light', 'nav' => 'events', 'wing' => 'events', 'active' => '' ) ); ?>

  <!-- 1 FAQ -->
  <section style=" padding:44px 20px 30px 20px; background:#F3F1FC; border-bottom:1px solid #E1DEF3;">
    <span class="eyebrow"<?php echo crux_edit_attr( 'faq', 'faq_small_heading_1' ); ?>><?php echo crux_h( 'faq', 'faq_small_heading_1' ); ?></span>
    <h1 class="bebas" style="font-size:44px; margin:14px 0px 14px 0px; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_1' ); ?>><?php echo crux_h( 'faq', 'faq_heading_1' ); ?></h1>
    <p style="font-size:16px; line-height:1.65; color:#5A5F86; max-width:620px; margin:0px 0px 24px 0px;" class="reveal"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_1' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_1' ); ?></p>
    <div style="display:flex; gap:10px; flex-wrap:wrap;" class="reveal" data-m="ctas"><a href="#events" style="background:#002671; color:#FFFFFF; font-weight:700; font-size:13.5px; padding:12px 24px 12px 24px; --sl:7px;" class="bx"<?php echo crux_edit_attr( 'faq', 'faq_button_1' ); ?>><?php echo crux_h( 'faq', 'faq_button_1' ); ?></a><a href="#consultancy" style="background:#8C7AE6; color:#10142E; font-weight:700; font-size:13.5px; padding:12px 24px 12px 24px; --sl:7px;" class="bx"<?php echo crux_edit_attr( 'faq', 'faq_button_2' ); ?>><?php echo crux_h( 'faq', 'faq_button_2' ); ?></a></div>
  </section>
  <section style=" padding:0px 20px 40px 20px;">
    <div id="events" style="display:grid; grid-template-columns:320px 1fr; gap:64px; align-items:start; padding:44px 0px 44px 0px; border-top:1.5px solid #E1DEF3;" class="reveal" data-m="g1">
      <div style="position:sticky; top:24px;" class="reveal" data-m="static"><span class="eyebrow" style="color:#002671;"<?php echo crux_edit_attr( 'faq', 'faq_small_heading_2' ); ?>><?php echo crux_h( 'faq', 'faq_small_heading_2' ); ?></span><h2 class="bebas" style="font-size:34px; margin:12px 0px 12px 0px; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_2' ); ?>><?php echo crux_h( 'faq', 'faq_heading_2' ); ?></h2><p style="font-size:14.5px; line-height:1.65; color:#5A5F86; margin:0px 0px 0px 0px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_2' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_2' ); ?></p></div>
      <div style="display:flex; flex-direction:column; gap:12px;" class="reveal">
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_3' ); ?>><?php echo crux_h( 'faq', 'faq_heading_3' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#002671; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_3' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_3' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_4' ); ?>><?php echo crux_h( 'faq', 'faq_heading_4' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#002671; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_4' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_4' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_5' ); ?>><?php echo crux_h( 'faq', 'faq_heading_5' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#002671; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;">Our office is at <?php echo esc_html( crux_address( false ) ); ?>. We plan and run events across the UK, and our on-site coordination covers destination weddings and corporate retreats too.</p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_6' ); ?>><?php echo crux_h( 'faq', 'faq_heading_6' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#002671; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"><?php echo crux_h( 'faq', 'faq_paragraph_5' ); ?> <a href="<?php echo esc_url( 'mailto:' . antispambot( crux_opt( 'email' ) ) ); ?>" style="color:#002671; font-weight:600; text-decoration:underline;"><?php echo esc_html( antispambot( crux_opt( 'email' ) ) ); ?></a> or call <?php echo esc_html( crux_opt( 'phone_consult' ) ); ?>. Tell us the type of event, the date and roughly how many guests, and we will take it from there.</p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_7' ); ?>><?php echo crux_h( 'faq', 'faq_heading_7' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#002671; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_6' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_6' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_8' ); ?>><?php echo crux_h( 'faq', 'faq_heading_8' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#002671; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_7' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_7' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_9' ); ?>><?php echo crux_h( 'faq', 'faq_heading_9' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#002671; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_8' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_8' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_10' ); ?>><?php echo crux_h( 'faq', 'faq_heading_10' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#002671; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_9' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_9' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_11' ); ?>><?php echo crux_h( 'faq', 'faq_heading_11' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#002671; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_10' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_10' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_12' ); ?>><?php echo crux_h( 'faq', 'faq_heading_12' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#002671; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_11' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_11' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_13' ); ?>><?php echo crux_h( 'faq', 'faq_heading_13' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#002671; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_12' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_12' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_14' ); ?>><?php echo crux_h( 'faq', 'faq_heading_14' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#002671; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_13' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_13' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_15' ); ?>><?php echo crux_h( 'faq', 'faq_heading_15' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#002671; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_14' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_14' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_16' ); ?>><?php echo crux_h( 'faq', 'faq_heading_16' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#002671; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_15' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_15' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_17' ); ?>><?php echo crux_h( 'faq', 'faq_heading_17' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#002671; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_16' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_16' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_18' ); ?>><?php echo crux_h( 'faq', 'faq_heading_18' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#002671; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_17' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_17' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_19' ); ?>><?php echo crux_h( 'faq', 'faq_heading_19' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#002671; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_18' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_18' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_20' ); ?>><?php echo crux_h( 'faq', 'faq_heading_20' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#002671; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_19' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_19' ); ?></p></details>
      </div>
    </div>
    <div id="consultancy" style="display:grid; grid-template-columns:320px 1fr; gap:64px; align-items:start; padding:44px 0px 44px 0px; border-top:1.5px solid #E1DEF3;" class="reveal" data-m="g1">
      <div style="position:sticky; top:24px;" data-m="static"><span class="eyebrow" style="color:#6C58DB;"<?php echo crux_edit_attr( 'faq', 'faq_small_heading_3' ); ?>><?php echo crux_h( 'faq', 'faq_small_heading_3' ); ?></span><h2 class="bebas" style="font-size:34px; margin:12px 0px 12px 0px; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_21' ); ?>><?php echo crux_h( 'faq', 'faq_heading_21' ); ?></h2><p style="font-size:14.5px; line-height:1.65; color:#5A5F86; margin:0px 0px 0px 0px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_20' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_20' ); ?></p></div>
      <div style="display:flex; flex-direction:column; gap:12px;">
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_22' ); ?>><?php echo crux_h( 'faq', 'faq_heading_22' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#8C7AE6; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_21' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_21' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_23' ); ?>><?php echo crux_h( 'faq', 'faq_heading_23' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#8C7AE6; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_22' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_22' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_24' ); ?>><?php echo crux_h( 'faq', 'faq_heading_24' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#8C7AE6; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_23' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_23' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_25' ); ?>><?php echo crux_h( 'faq', 'faq_heading_25' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#8C7AE6; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_24' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_24' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_26' ); ?>><?php echo crux_h( 'faq', 'faq_heading_26' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#8C7AE6; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_25' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_25' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_27' ); ?>><?php echo crux_h( 'faq', 'faq_heading_27' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#8C7AE6; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_26' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_26' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_28' ); ?>><?php echo crux_h( 'faq', 'faq_heading_28' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#8C7AE6; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_27' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_27' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_29' ); ?>><?php echo crux_h( 'faq', 'faq_heading_29' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#8C7AE6; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_28' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_28' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_30' ); ?>><?php echo crux_h( 'faq', 'faq_heading_30' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#8C7AE6; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_29' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_29' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_31' ); ?>><?php echo crux_h( 'faq', 'faq_heading_31' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#8C7AE6; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_30' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_30' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_32' ); ?>><?php echo crux_h( 'faq', 'faq_heading_32' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#8C7AE6; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_31' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_31' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_33' ); ?>><?php echo crux_h( 'faq', 'faq_heading_33' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#8C7AE6; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_32' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_32' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_34' ); ?>><?php echo crux_h( 'faq', 'faq_heading_34' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#8C7AE6; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_33' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_33' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_35' ); ?>><?php echo crux_h( 'faq', 'faq_heading_35' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#8C7AE6; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_34' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_34' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_36' ); ?>><?php echo crux_h( 'faq', 'faq_heading_36' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#8C7AE6; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_35' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_35' ); ?></p></details>
        <details style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:16px; padding:0px 26px 0px 26px;"><summary style="list-style:none; cursor:pointer; display:flex; justify-content:space-between; align-items:center; gap:20px; padding:22px 0px 22px 0px;"><h3 style="font-size:17px; margin:0px 0px 0px 0px; font-weight:700; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_37' ); ?>><?php echo crux_h( 'faq', 'faq_heading_37' ); ?></h3><span class="fq-plus" style="flex:0 0 32px; height:32px; border-radius:50%; background:#8C7AE6; color:#FFFFFF; display:flex; align-items:center; justify-content:center; font-size:20px; line-height:1; transition:transform .25s ease;">+</span></summary><p style="font-size:15px; line-height:1.75; color:#3A3F66; margin:0px 0px 24px 0px; max-width:680px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_36' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_36' ); ?></p></details>
      </div>
    </div>

    <div style="border-top:1.5px solid #E1DEF3; padding:48px 0px 30px 0px; display:flex; justify-content:space-between; align-items:center; gap:24px;" class="reveal" data-m="stack"><div><h3 class="bebas" style="font-size:32px; margin:0px 0px 6px 0px; color:#10142E;"<?php echo crux_edit_attr( 'faq', 'faq_heading_38' ); ?>><?php echo crux_h( 'faq', 'faq_heading_38' ); ?></h3><p style="font-size:15px; color:#5A5F86; margin:0px 0px 0px 0px;"<?php echo crux_edit_attr( 'faq', 'faq_paragraph_37' ); ?>><?php echo crux_h( 'faq', 'faq_paragraph_37' ); ?></p></div><a href="<?php echo crux_url( 'faq', 'faq_button_3_url' ); ?>" style="background:#8C7AE6; color:#10142E; font-weight:700; font-size:15px; padding:16px 30px 16px 30px; --sl:10px;" class="bx"<?php echo crux_edit_attr( 'faq', 'faq_button_3' ); ?>><?php echo crux_h( 'faq', 'faq_button_3' ); ?></a></div>
  </section>

  <?php get_template_part( 'parts/site-footer', null, array( 'skin' => 'light', 'prefooter' => 'events-light', 'wing' => 'events' ) ); ?>
  <div class="msw">
  <div class="crux-sw-pod crux-sw-pod--light" style="pointer-events:auto; display:inline-flex; align-items:center; padding:1.5px; background:linear-gradient(135deg, #C4BAEE 0%, #A99CE0 100%); clip-path:polygon(8px 0, 100% 0, calc(100% - 8px) 100%, 0 100%); box-shadow:0 14px 36px rgba(16,20,46,0.22); filter:drop-shadow(0 4px 12px rgba(16,20,46,0.12));">
    <div class="crux-sw-inner" style="display:inline-flex; align-items:center; background:#EBE7F7; padding:4px; gap:4px; clip-path:polygon(7px 0, 100% 0, calc(100% - 7px) 100%, 0 100%);">
      <a href="<?php echo esc_url( home_url( "/" ) ); ?>" class="crux-sw-tab crux-sw-tab--active-events" style="display:inline-flex; align-items:center; justify-content:center; padding:11px 22px; min-width:140px; font-size:13px; font-weight:700; letter-spacing:0.3px; text-transform:uppercase; text-decoration:none; line-height:1.2; background:#1E48B0; color:#FFFFFF; clip-path:polygon(6px 0, 100% 0, calc(100% - 6px) 100%, 0 100%); box-shadow:0 2px 8px rgba(30,72,176,0.4);">
        <span<?php echo crux_edit_attr( 'faq', 'faq_text_1' ); ?>><?php echo crux_h( 'faq', 'faq_text_1' ); ?></span>
      </a>
      <a href="<?php echo esc_url( home_url( "/consultancy/" ) ); ?>" class="crux-sw-tab crux-sw-tab--inactive-light" style="display:inline-flex; align-items:center; justify-content:center; padding:11px 22px; min-width:140px; font-size:13px; font-weight:600; letter-spacing:0.3px; text-transform:uppercase; text-decoration:none; line-height:1.2; background:transparent; color:#4A5073; clip-path:polygon(6px 0, 100% 0, calc(100% - 6px) 100%, 0 100%); transition:all .2s ease;">
        <span<?php echo crux_edit_attr( 'faq', 'faq_text_2' ); ?>><?php echo crux_h( 'faq', 'faq_text_2' ); ?></span><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" style="margin-left:6px; display:inline-block; vertical-align:middle;"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>
      </a>
    </div>
  </div>
</div></div></div>







<?php get_footer(); ?>
