<?php
/**
 * Template Name: Crux Nxtion - Template
 *
 * @package CruxNxtion
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<?php crux_use_page_css( 'legal' ); get_header( null, array( 'body_bg' => '#FFFFFF', 'root_bg' => '#FFFFFF', 'skin' => 'light', 'nav' => 'consultancy', 'wing' => 'consultancy', 'active' => '' ) ); ?>

  <!-- PAGE HEADING -->
  <section style=" padding:44px 20px 50px 20px; display:grid; grid-template-columns:1.2fr 0.8fr; gap:60px; align-items:end;" data-m="g1">
    <div class="reveal"><span class="eyebrow"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_small_heading_1' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_small_heading_1' ); ?></span><h1 class="bebas" style="font-size:52px; margin:16px 0px 0px 0px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_heading_1' ); ?>><?php echo crux_rich( 'services_consultancy', 'page_heading_heading_1' ); ?></h1></div>
    <p style="font-size:16px; line-height:1.75; color:#3A3F66; margin:0px 0px 0px 0px;" class="reveal"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_1' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_paragraph_1' ); ?></p>
  </section>
  <section style=" padding:20px 20px 44px 20px;"><div style="display:flex; flex-direction:column; gap:28px;" class="reveal">
      <div style="display:grid; grid-template-columns:0.9fr 1fr; background:#F3F1FC; border:1.5px solid #E1DEF3; border-radius:22px; overflow:hidden;" data-m="g1">
        <div style="order:1; position:relative; min-height:400px;" class="reveal" data-m="tile">
          <img src="<?php echo crux_img_url( 'services_consultancy', 'page_heading_photo_1' ); ?>" alt="" style="position:absolute; inset:0; width:100%; height:100%; object-fit:cover; filter:brightness(0.85);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_photo_1' ); ?>>
          <div style="position:absolute; inset:0; background:linear-gradient(160deg, rgba(140,122,230,0.3) 0%, rgba(16,20,46,0.55) 100%);"></div>
          <div class="ticket-stub" style="position:absolute; left:0; top:36px; background:var(--crux-purple,#8C7AE6); padding:14px 22px 14px 26px; border-radius:0 10px 10px 0;"><span class="bebas" style="font-size:30px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_1' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_1' ); ?></span></div>
        </div>
        <div style="order:2; padding:44px 20px 44px 20px;" class="reveal">
          <h3 class="bebas" style="font-size:34px; margin:0px 0px 18px 0px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_heading_2' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_heading_2' ); ?></h3>
          <div style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:14px 14px 14px 4px; padding:16px 18px 16px 18px; margin-bottom:12px;"><span style="font-size:10.5px; letter-spacing:1.5px; text-transform:uppercase; color:#D9182A; font-weight:700;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_2' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_2' ); ?></span><p style="font-size:16px; font-weight:600; margin:6px 0px 0px 0px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_2' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_paragraph_2' ); ?></p></div>
          <div style="background:var(--crux-purple,#8C7AE6); border-radius:14px 14px 4px 14px; padding:16px 18px 16px 18px; margin-bottom:22px;"><span style="font-size:10.5px; letter-spacing:1.5px; text-transform:uppercase; color:var(--crux-ink2,#10142E); font-weight:800;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_3' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_3' ); ?></span><p style="font-size:14.5px; line-height:1.6; font-weight:600; margin:6px 0px 0px 0px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_3' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_paragraph_3' ); ?></p></div>
          <p style="font-size:14px; line-height:1.75; color:#3A3F66; margin:0px 0px 20px 0px;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_4' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_paragraph_4' ); ?></p>
          <span class="eyebrow"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_small_heading_2' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_small_heading_2' ); ?></span>
          <div style="display:flex; gap:10px; flex-wrap:wrap; margin-top:12px;" data-m="wrap"><span style="color:#3A3F66; font-size:12px; font-weight:600; padding:8px 16px 8px 16px; --sl:6px; --bc:#D2CEEA;" class="bx"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_4' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_4' ); ?></span><span style="color:#3A3F66; font-size:12px; font-weight:600; padding:8px 16px 8px 16px; --sl:6px; --bc:#D2CEEA;" class="bx"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_5' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_5' ); ?></span><span style="color:#3A3F66; font-size:12px; font-weight:600; padding:8px 16px 8px 16px; --sl:6px; --bc:#D2CEEA;" class="bx"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_6' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_6' ); ?></span></div>
          <p style="font-size:12.5px; color:#5A5F86; margin:18px 0px 0px 0px;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_5' ); ?>><?php echo crux_rich( 'services_consultancy', 'page_heading_paragraph_5' ); ?></p>
        </div>
      </div>
      <div style="display:grid; grid-template-columns:1fr 0.9fr; background:#F3F1FC; border:1.5px solid #E1DEF3; border-radius:22px; overflow:hidden;" data-m="g1">
        <div style="order:2; position:relative; min-height:400px;" data-m="tile">
          <img src="<?php echo crux_img_url( 'services_consultancy', 'page_heading_photo_2' ); ?>" alt="" style="position:absolute; inset:0; width:100%; height:100%; object-fit:cover; filter:brightness(0.85);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_photo_2' ); ?>>
          <div style="position:absolute; inset:0; background:linear-gradient(160deg, rgba(140,122,230,0.3) 0%, rgba(16,20,46,0.55) 100%);"></div>
          <div class="ticket-stub" style="position:absolute; left:0; top:36px; background:var(--crux-purple,#8C7AE6); padding:14px 22px 14px 26px; border-radius:0 10px 10px 0;"><span class="bebas" style="font-size:30px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_7' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_7' ); ?></span></div>
        </div>
        <div style="order:1; padding:44px 20px 44px 20px;">
          <h3 class="bebas" style="font-size:34px; margin:0px 0px 18px 0px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_heading_3' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_heading_3' ); ?></h3>
          <div style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:14px 14px 14px 4px; padding:16px 18px 16px 18px; margin-bottom:12px;"><span style="font-size:10.5px; letter-spacing:1.5px; text-transform:uppercase; color:#D9182A; font-weight:700;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_2' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_2' ); ?></span><p style="font-size:16px; font-weight:600; margin:6px 0px 0px 0px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_6' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_paragraph_6' ); ?></p></div>
          <div style="background:var(--crux-purple,#8C7AE6); border-radius:14px 14px 4px 14px; padding:16px 18px 16px 18px; margin-bottom:22px;"><span style="font-size:10.5px; letter-spacing:1.5px; text-transform:uppercase; color:var(--crux-ink2,#10142E); font-weight:800;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_3' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_3' ); ?></span><p style="font-size:14.5px; line-height:1.6; font-weight:600; margin:6px 0px 0px 0px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_7' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_paragraph_7' ); ?></p></div>
          <p style="font-size:14px; line-height:1.75; color:#3A3F66; margin:0px 0px 20px 0px;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_8' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_paragraph_8' ); ?></p>
          <span class="eyebrow"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_small_heading_2' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_small_heading_2' ); ?></span>
          <div style="display:flex; gap:10px; flex-wrap:wrap; margin-top:12px;" data-m="wrap"><span style="color:#3A3F66; font-size:12px; font-weight:600; padding:8px 16px 8px 16px; --sl:6px; --bc:#D2CEEA;" class="bx"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_8' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_8' ); ?></span><span style="color:#3A3F66; font-size:12px; font-weight:600; padding:8px 16px 8px 16px; --sl:6px; --bc:#D2CEEA;" class="bx"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_9' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_9' ); ?></span><span style="color:#3A3F66; font-size:12px; font-weight:600; padding:8px 16px 8px 16px; --sl:6px; --bc:#D2CEEA;" class="bx"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_10' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_10' ); ?></span></div>
          <p style="font-size:12.5px; color:#5A5F86; margin:18px 0px 0px 0px;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_9' ); ?>><?php echo crux_rich( 'services_consultancy', 'page_heading_paragraph_9' ); ?></p>
        </div>
      </div>
      <div style="display:grid; grid-template-columns:0.9fr 1fr; background:#F3F1FC; border:1.5px solid #E1DEF3; border-radius:22px; overflow:hidden;" data-m="g1">
        <div style="order:1; position:relative; min-height:400px;" data-m="tile">
          <img src="<?php echo crux_img_url( 'services_consultancy', 'page_heading_photo_3' ); ?>" alt="" style="position:absolute; inset:0; width:100%; height:100%; object-fit:cover; filter:brightness(0.85);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_photo_3' ); ?>>
          <div style="position:absolute; inset:0; background:linear-gradient(160deg, rgba(140,122,230,0.3) 0%, rgba(16,20,46,0.55) 100%);"></div>
          <div class="ticket-stub" style="position:absolute; left:0; top:36px; background:var(--crux-purple,#8C7AE6); padding:14px 22px 14px 26px; border-radius:0 10px 10px 0;"><span class="bebas" style="font-size:30px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_11' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_11' ); ?></span></div>
        </div>
        <div style="order:2; padding:44px 20px 44px 20px;">
          <h3 class="bebas" style="font-size:34px; margin:0px 0px 18px 0px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_heading_4' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_heading_4' ); ?></h3>
          <div style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:14px 14px 14px 4px; padding:16px 18px 16px 18px; margin-bottom:12px;"><span style="font-size:10.5px; letter-spacing:1.5px; text-transform:uppercase; color:#D9182A; font-weight:700;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_2' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_2' ); ?></span><p style="font-size:16px; font-weight:600; margin:6px 0px 0px 0px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_10' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_paragraph_10' ); ?></p></div>
          <div style="background:var(--crux-purple,#8C7AE6); border-radius:14px 14px 4px 14px; padding:16px 18px 16px 18px; margin-bottom:22px;"><span style="font-size:10.5px; letter-spacing:1.5px; text-transform:uppercase; color:var(--crux-ink2,#10142E); font-weight:800;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_3' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_3' ); ?></span><p style="font-size:14.5px; line-height:1.6; font-weight:600; margin:6px 0px 0px 0px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_11' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_paragraph_11' ); ?></p></div>
          <p style="font-size:14px; line-height:1.75; color:#3A3F66; margin:0px 0px 20px 0px;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_12' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_paragraph_12' ); ?></p>
          <span class="eyebrow"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_small_heading_2' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_small_heading_2' ); ?></span>
          <div style="display:flex; gap:10px; flex-wrap:wrap; margin-top:12px;" data-m="wrap"><span style="color:#3A3F66; font-size:12px; font-weight:600; padding:8px 16px 8px 16px; --sl:6px; --bc:#D2CEEA;" class="bx"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_12' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_12' ); ?></span><span style="color:#3A3F66; font-size:12px; font-weight:600; padding:8px 16px 8px 16px; --sl:6px; --bc:#D2CEEA;" class="bx"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_13' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_13' ); ?></span><span style="color:#3A3F66; font-size:12px; font-weight:600; padding:8px 16px 8px 16px; --sl:6px; --bc:#D2CEEA;" class="bx"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_14' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_14' ); ?></span></div>
          <p style="font-size:12.5px; color:#5A5F86; margin:18px 0px 0px 0px;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_13' ); ?>><?php echo crux_rich( 'services_consultancy', 'page_heading_paragraph_13' ); ?></p>
        </div>
      </div>
      <div style="display:grid; grid-template-columns:1fr 0.9fr; background:#F3F1FC; border:1.5px solid #E1DEF3; border-radius:22px; overflow:hidden;" data-m="g1">
        <div style="order:2; position:relative; min-height:400px;" data-m="tile">
          <img src="<?php echo crux_img_url( 'services_consultancy', 'page_heading_photo_4' ); ?>" alt="" style="position:absolute; inset:0; width:100%; height:100%; object-fit:cover; filter:brightness(0.85);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_photo_4' ); ?>>
          <div style="position:absolute; inset:0; background:linear-gradient(160deg, rgba(140,122,230,0.3) 0%, rgba(16,20,46,0.55) 100%);"></div>
          <div class="ticket-stub" style="position:absolute; left:0; top:36px; background:var(--crux-purple,#8C7AE6); padding:14px 22px 14px 26px; border-radius:0 10px 10px 0;"><span class="bebas" style="font-size:30px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_15' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_15' ); ?></span></div>
        </div>
        <div style="order:1; padding:44px 20px 44px 20px;">
          <h3 class="bebas" style="font-size:34px; margin:0px 0px 18px 0px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_heading_5' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_heading_5' ); ?></h3>
          <div style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:14px 14px 14px 4px; padding:16px 18px 16px 18px; margin-bottom:12px;"><span style="font-size:10.5px; letter-spacing:1.5px; text-transform:uppercase; color:#D9182A; font-weight:700;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_2' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_2' ); ?></span><p style="font-size:16px; font-weight:600; margin:6px 0px 0px 0px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_14' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_paragraph_14' ); ?></p></div>
          <div style="background:var(--crux-purple,#8C7AE6); border-radius:14px 14px 4px 14px; padding:16px 18px 16px 18px; margin-bottom:22px;"><span style="font-size:10.5px; letter-spacing:1.5px; text-transform:uppercase; color:var(--crux-ink2,#10142E); font-weight:800;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_3' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_3' ); ?></span><p style="font-size:14.5px; line-height:1.6; font-weight:600; margin:6px 0px 0px 0px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_15' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_paragraph_15' ); ?></p></div>
          <p style="font-size:14px; line-height:1.75; color:#3A3F66; margin:0px 0px 20px 0px;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_16' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_paragraph_16' ); ?></p>
          <span class="eyebrow"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_small_heading_2' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_small_heading_2' ); ?></span>
          <div style="display:flex; gap:10px; flex-wrap:wrap; margin-top:12px;" data-m="wrap"><span style="color:#3A3F66; font-size:12px; font-weight:600; padding:8px 16px 8px 16px; --sl:6px; --bc:#D2CEEA;" class="bx"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_16' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_16' ); ?></span><span style="color:#3A3F66; font-size:12px; font-weight:600; padding:8px 16px 8px 16px; --sl:6px; --bc:#D2CEEA;" class="bx"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_17' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_17' ); ?></span><span style="color:#3A3F66; font-size:12px; font-weight:600; padding:8px 16px 8px 16px; --sl:6px; --bc:#D2CEEA;" class="bx"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_18' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_18' ); ?></span></div>
          <p style="font-size:12.5px; color:#5A5F86; margin:18px 0px 0px 0px;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_17' ); ?>><?php echo crux_rich( 'services_consultancy', 'page_heading_paragraph_17' ); ?></p>
        </div>
      </div>
      <div style="display:grid; grid-template-columns:0.9fr 1fr; background:#F3F1FC; border:1.5px solid #E1DEF3; border-radius:22px; overflow:hidden;" data-m="g1">
        <div style="order:1; position:relative; min-height:400px;" data-m="tile">
          <img src="<?php echo crux_img_url( 'services_consultancy', 'page_heading_photo_5' ); ?>" alt="" style="position:absolute; inset:0; width:100%; height:100%; object-fit:cover; filter:brightness(0.85);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_photo_5' ); ?>>
          <div style="position:absolute; inset:0; background:linear-gradient(160deg, rgba(140,122,230,0.3) 0%, rgba(16,20,46,0.55) 100%);"></div>
          <div class="ticket-stub" style="position:absolute; left:0; top:36px; background:var(--crux-purple,#8C7AE6); padding:14px 22px 14px 26px; border-radius:0 10px 10px 0;"><span class="bebas" style="font-size:30px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_19' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_19' ); ?></span></div>
        </div>
        <div style="order:2; padding:44px 20px 44px 20px;">
          <h3 class="bebas" style="font-size:34px; margin:0px 0px 18px 0px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_heading_6' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_heading_6' ); ?></h3>
          <div style="background:#FFFFFF; border:1.5px solid #E1DEF3; border-radius:14px 14px 14px 4px; padding:16px 18px 16px 18px; margin-bottom:12px;"><span style="font-size:10.5px; letter-spacing:1.5px; text-transform:uppercase; color:#D9182A; font-weight:700;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_2' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_2' ); ?></span><p style="font-size:16px; font-weight:600; margin:6px 0px 0px 0px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_18' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_paragraph_18' ); ?></p></div>
          <div style="background:var(--crux-purple,#8C7AE6); border-radius:14px 14px 4px 14px; padding:16px 18px 16px 18px; margin-bottom:22px;"><span style="font-size:10.5px; letter-spacing:1.5px; text-transform:uppercase; color:var(--crux-ink2,#10142E); font-weight:800;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_3' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_3' ); ?></span><p style="font-size:14.5px; line-height:1.6; font-weight:600; margin:6px 0px 0px 0px; color:var(--crux-ink2,#10142E);"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_19' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_paragraph_19' ); ?></p></div>
          <p style="font-size:14px; line-height:1.75; color:#3A3F66; margin:0px 0px 20px 0px;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_20' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_paragraph_20' ); ?></p>
          <span class="eyebrow"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_small_heading_2' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_small_heading_2' ); ?></span>
          <div style="display:flex; gap:10px; flex-wrap:wrap; margin-top:12px;" data-m="wrap"><span style="color:#3A3F66; font-size:12px; font-weight:600; padding:8px 16px 8px 16px; --sl:6px; --bc:#D2CEEA;" class="bx"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_20' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_20' ); ?></span><span style="color:#3A3F66; font-size:12px; font-weight:600; padding:8px 16px 8px 16px; --sl:6px; --bc:#D2CEEA;" class="bx"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_21' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_21' ); ?></span><span style="color:#3A3F66; font-size:12px; font-weight:600; padding:8px 16px 8px 16px; --sl:6px; --bc:#D2CEEA;" class="bx"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_22' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_22' ); ?></span></div>
          <p style="font-size:12.5px; color:#5A5F86; margin:18px 0px 0px 0px;"<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_paragraph_21' ); ?>><?php echo crux_rich( 'services_consultancy', 'page_heading_paragraph_21' ); ?></p>
        </div>
      </div></div></section>


  <div style="background:var(--crux-ink2,#10142E);">
  <?php get_template_part( 'parts/site-footer', null, array( 'skin' => 'light', 'prefooter' => 'services', 'wing' => 'consultancy' ) ); ?>
  </div>

<div class="msw">
  <div class="crux-sw-pod crux-sw-pod--light" style="pointer-events:auto; display:inline-flex; align-items:center; padding:1.5px; background:linear-gradient(135deg, #C4BAEE 0%, #A99CE0 100%); clip-path:polygon(8px 0, 100% 0, calc(100% - 8px) 100%, 0 100%); box-shadow:0 14px 36px rgba(16,20,46,0.22); filter:drop-shadow(0 4px 12px rgba(16,20,46,0.12));">
    <div class="crux-sw-inner" style="display:inline-flex; align-items:center; background:#EBE7F7; padding:4px; gap:4px; clip-path:polygon(7px 0, 100% 0, calc(100% - 7px) 100%, 0 100%);">
      <a href="<?php echo esc_url( home_url( "/" ) ); ?>" class="crux-sw-tab crux-sw-tab--inactive-light" style="display:inline-flex; align-items:center; justify-content:center; padding:11px 22px; min-width:140px; font-size:13px; font-weight:600; letter-spacing:0.3px; text-transform:uppercase; text-decoration:none; line-height:1.2; background:transparent; color:#4A5073; clip-path:polygon(6px 0, 100% 0, calc(100% - 6px) 100%, 0 100%); transition:all .2s ease;">
        <span<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_23' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_23' ); ?></span><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" style="margin-left:6px; display:inline-block; vertical-align:middle;"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>
      </a>
      <a href="<?php echo esc_url( home_url( "/consultancy/" ) ); ?>" class="crux-sw-tab crux-sw-tab--active-consultancy" style="display:inline-flex; align-items:center; justify-content:center; padding:11px 22px; min-width:140px; font-size:13px; font-weight:700; letter-spacing:0.3px; text-transform:uppercase; text-decoration:none; line-height:1.2; background:var(--crux-violet,#6C58DB); color:#FFFFFF; clip-path:polygon(6px 0, 100% 0, calc(100% - 6px) 100%, 0 100%); box-shadow:0 2px 8px rgba(108,88,219,0.45);">
        <span<?php echo crux_edit_attr( 'services_consultancy', 'page_heading_text_24' ); ?>><?php echo crux_h( 'services_consultancy', 'page_heading_text_24' ); ?></span>
      </a>
    </div>
  </div>
</div></div></div>





<?php get_footer(); ?>
